mate-desktop/mate-panel

applets/notification_area/na-tray-manager.c

from upstream commit:
https://git.gnome.org/browse/gnome-panel/commit/applets/notification_area/na-tray-manager.c?id=2adbcc5308577d864b09062a3343b9f8dbcdcd7f

[1.8] notification area: prevent crash

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/panel-background.c
mate-panel/panel-background.h

Working with style properties is useless, because GTK have only stubs here. 
GTK3 Background logic already in panel_background_prepare.

Remove change_background_for_widget from GTK3 build (it is useless.)

---

help/mate-panel/C/goseditmainmenu.xml

- this is part of gnome and named as mate guide which is confusing

remove link to system-admin-guide

---

mate-panel/panel-toplevel.c
mate-panel/panel-xutils.c
mate-panel/panel-xutils.h

Both functions have exactly the same semantics, so prefer the Gtk+ builtin. That's one function less to worry about Gtk+2 vs 3 compatibility (or Wayland).
In addition, this also fixes issue #280.

replace panel_xutils_set_window_type with gtk_window_set_type_hint

---

mate-panel/button-widget.c
mate-panel/panel-toplevel.c

gdk_window_set_geometry_hints accept 0 as flags when geometry is null
return 1px width/height while image is not loadded

eliminate criticals

---

mate-panel/applet.c

Until position calculations are refactored to fix the issue of the panel applets
getting reordered on resolution changes don't save position/right-stick on locked applets.
This partially fixes https://github.com/mate-desktop/mate-panel/issues/84 (it fixes it as long as applets remain locked. Unlocked right-stick applets are still vulnerable ... we need a much bigger solution for this, possibly redesign the way we handle coordinates).

Don't change position/right-stick of locked applets

---

applets/clock/clock.c

this fixes https://github.com/mate-desktop/mate-panel/commit/c71b55007d73485bfc3fc1d30c42cb329bc30125

clock applet: fix ubuntu ambiant-mate gtk2 theming

---

mate-panel/xstuff.c

ported from:
https://git.gnome.org/browse/gnome-panel/commit/?id=8c275a2adf4ad99297a17cabf251344837620831
https://git.gnome.org/browse/gnome-panel/commit/?id=be33e799d968a073c0a8856c96d11e8594b88bc4

don't destroy a widget in its draw/expose signal

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/mate-panel-applet-frame.c
mate-panel/panel-background.c
mate-panel/panel-background.h
mate-panel/panel-menu-bar.c
mate-panel/panel-separator.c
mate-panel/panel-widget.c

This fixes the background for GTK+ 3 themes which don't support mate-panel explicitly. Themes could still overwrite the background if they want in the usual way.
To get back exactly the previous state, you can add the following lines to your themes:
Before other declarations: `.mate-panel-menu-bar {background: transparent;} `
After other declarations (these background settings were ignored previously): `PanelToplevel, PanelMenuBar, PanelSeparator {background: transparent;} `

Don't set the panel transparent by default

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/panel-background.c

We don't need to reset style when adding/removing classes. It was a regression in commit 6f634c680fbc5ee5051253554f2710e39f9ea80a

gtk3: fix infinite loop with Traditional themes

---

data/org.mate.panel.menubar.gschema.xml.in
mate-panel/panel-menu-items.c
mate-panel/panel-schemas.h

Hi everyone!
It annoyed me for some time that I could only have 8 bookmarks in the places menu before a submenu was created, even though my screen resolution would allow for quite a few more...
Upon investigating, I could only find this: http://ubuntuforums.org/showthread.php?t=1066964
I was thinking "This should really be a setting in dconf or something". Some tinkering later, I got it working and here it is! ;)
Please review. I'm sure I made some stupid rookie mistake or two.
For example the new gschema.xml; I had to manually copy it to /usr/share/glib-2.0/schemas and run glib-compile-schemas after make install. What's the right way to fix that?
Do I need to check the GSettings pointer for NULL before using g_settings_get_int() ?
If the schema does not exist, the pointer is NULL and I …

Make MAX_ITEMS_OR_SUBMENU configurable.

---

applets/clock/clock.c

Unless I'm missing something I don't see a reason for setting "use_markup = FALSE;" at 643 and then again at 648

clock: remove useless duplication

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/panel-applet-frame.c
mate-panel/panel-force-quit.c
mate-panel/panel-toplevel.c
mate-panel/panel-widget.c

Gtk_Seat is already used but this way it fixes also deprecated device_ungrab.
Taken from https://git.gnome.org/browse/gnome-panel/log/?qt=grep&q=device
Also, some Gtk_Version_Checks are corrected from previous commits.
See, https://github.com/mate-desktop/mate-panel/pull/466

avoid deprecated device_ungrab

---

applets/clock/calendar-window.c

Force minimum width for calendar window to stop jumping (on locations open/close) in themes that don't enlarge calendar from the rather small default. Set the minimum height smaller than any theme would set it as it otherwise just puts blank space under the last row rather than spacing out the numbers.
Fix for https://github.com/mate-desktop/mate-panel/issues/491

Calendar Window: force minimum size

---

applets/clock/clock.c
applets/wncklet/showdesktop.c
applets/wncklet/window-list.c

This stops most GTK warnings from the panel itself, except that themes putting a non-zero width border on the clock button will still throw a 1px underallocation warning.  With no border there no warnings from clock but themers should not lose this. The rest of the warnings from the panel itself are gone.

Fix most GTK warnings from mate-panel

---

mate-panel/panel-menu-bar.c
mate-panel/panel-menu-button.c

This patch re-purposes the existing fallback support for the now obsolete
`matemenu-simple-editor` to add (optional) support for [menulibre](https://smdavis.us/projects/menulibre/). The logic is simple, if `menulibre` is installed use it in preference to `mozo`. If `menulibre` is not available, fallback to `mozo`.
The rationale is this; if you've installed `menulibre` you want to use it in preference to `mozo`. Menulibre offers a super-set of menu editing capabilities compared to `mozo` and is growing in popularity. This change will allow distro maintainers to chose which menu editor they want to offer.

Add (optional) support for menulibre.

---

applets/clock/clock.c

Mentioned at https://github.com/mate-desktop/mate-panel/issues/509. Well, I've never seen any warnings from this part of code (don't know why), but for the sake of completeness...

clock: fix remaining deprecation for GTK+ >= 3.20

---

mate-panel/panel-toplevel.c

Fix the logic guarding against updating the name and description so
that it properly checks against strings in the same locale.
This prevents spamming accessibility 'accessible-name' change events,
avoiding some noise when interacting with the panel.

Don't spam accessible name changes when it is translated

---

mate-panel/launcher.c
mate-panel/panel-ditem-editor.c

restore ability to configure launcher's custom icon which degradated after switching on g_app_info_get_icon
also update launcher state after saving launcher's properties.
https://github.com/mate-desktop/mate-panel/issues/538

setup custom icon

---

applets/notification_area/libstatus-notifier-watcher/gf-sn-watcher-v0.c

The [SNI specification](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierWatcher/) doesn't explicitly state what should happen when trying to register again an already registered item, so it would seem only logical to forbid it.  Unfortunately, libappindicator tries re-registering pretty often, and even falls back to System Tray if it fails.  So in practice we need to be forgiving and pretend it's OK, or we get [a](https://github.com/mate-desktop/mate-panel/issues/539) [duplicate](https://ubuntu-mate.community/t/17-04-nm-applet-works-fine-but-shows-2-icons-in-the-system-tray/12020) System Tray item for this one.
Fixes #539.

status-notifier-watcher: Allow re-registration of already registered items

---

applets/notification_area/na-box.c

Properly forward orientation to the items.  This especially fixes SNI items height in vertical panels, but affects several details on all items.

notification-area: Fix item orientation

---

mate-panel/panel-widget.c

when changing panel orientation or rotating the screen itself,
panel might keep its old size, so some applets might appear
behind screen edge (until you restart the panel). same thing
might happen when enabling hide buttons.
fixes https://github.com/mate-desktop/mate-panel/issues/552
upstream commit with detailed problem description:
https://git.gnome.org/browse/gnome-panel/commit/?id=fc24d8fa623c4cf841eb5168cb1c250b4a84d4da
upstream commit with the actual fix:
https://git.gnome.org/browse/gnome-panel/commit/?id=4511f4466df0b163906794b4a32196226ccf90f3
yes, it's somewhat messed up there :)

properly fit expanded panel to smaller screen size

---

data/org.mate.panel.gschema.xml.in
mate-panel/panel-run-dialog.c

A key has been added to the gsettings schema that controls history size and the code of the run dialog has been changed to use that key. The default of 10 is preserved and the setting is only exposed via gsettings.
Note that this *pull request* includes https://github.com/mate-desktop/mate-panel/pull/560 because it is based on it.

Run dialog: Allow changing history size

---

data/org.mate.panel.gschema.xml.in
mate-panel/panel-run-dialog.c

As discussed in https://github.com/mate-desktop/mate-panel/pull/560, this patch adds a `GSettings` key `history-reverse-mate-run` to view the run dialog history in reverse order (*i.e. history stays the same*). Thus with this key enabled (by default disabled) the history is displayed with the least recent entry first and allows to select the most recent entry with the up key. **Important:** This patch includes https://github.com/mate-desktop/mate-panel/pull/561 as it is on top of it.
Downsides: Changing the setting will reverse the history when the run dialog is open. This can be solved by registering a signal handler to the `GSettings` object. (I didn't bother to do it, because it seemed too much work for too little gain.)

Reverse history

---

mate-panel/panel-menu-items.c

This is a runtime check, obviously.
https://bugzilla.gnome.org/show_bug.cgi?id=675393
taken from:
https://git.gnome.org/browse/gnome-panel/commit/?id=19a23e8
https://git.gnome.org/browse/gnome-panel/commit/?id=af73783
Fixes https://github.com/mate-desktop/mate-panel/issues/225#issuecomment-296941888
We like to follow caja changes.

panel: Use new GTK bookmarks location if using GTK+ >= 3.5.1

---

mate-panel/menu.c

fixes https://github.com/mate-desktop/mate-panel/issues/494

menu: fix crash when some .desktop file has empty Icon field

---

mate-panel/panel-widget.c

fixes https://github.com/mate-desktop/mate-panel/issues/504
have to repeat my change from 024f89bc7c8074f753120d9c8ec4bd839745984b
because of fallout from 225702b3c6a609065465c66f0f2739fc1d2184a9

fix moving applets between panels

---

libmate-panel-applet/mate-panel-applet.c

Avoid cairo function that seemed to be causing crashes related to setting geometry, use code copied from panel-background.c instead. Fixes https://github.com/mate-desktop/mate-panel/issues/604

fix applet crashes on transparent user-set panel bg

---

applets/clock/clock-utils.c
applets/fish/fish.c
applets/notification_area/main.c
applets/wncklet/wncklet.c
mate-panel/libpanel-util/panel-show.c
mate-panel/libpanel-util/panel-show.h

Tested on Debian Unstable. Uses NULL as the window, seems to work fine. Help tested from clock, window list, tray, fish, and panel context menu. Tested with applets both in and out of process and help always worked and never saw a redraw problem afterwards.

don't use deprecated gtk_show_uri

---

mate-panel/main.c

Fixes the build warning discussed here: 
* https://github.com/mate-desktop/mate-panel/pull/624#issuecomment-321738661

Add missing include.

---

applets/notification_area/main.c
data/org.mate.panel.gschema.xml.in

SNI Support triggers many changes and regressions.
This PR introduces a gsettings key to be able to disable it.

Add a gsettings key to enable/disable SNI Support

---

applets/clock/clock.c
applets/fish/fish.c
mate-panel/applet.c
mate-panel/panel-action-button.c

*On destroying applet disconnect signals for functions that otherwise segfaults with glib 2.53.4 or later.
*Fish: it's not always enough for a function to return immediately if applet destroyed anymore
*panel-action-button: suppress a warning

Fix crashes on moving/removing applets with glib 2.53.4 or later

---

mate-panel/panel-context-menu.c

It can happen that a panel configuration is so messed up, that only a reset helps.
Only a few users know how to do that.
This patch adds a context menu entry "Reset Panel", which enables a user to do that.
Internally the function behind "mate-panel --reset" is called.

Add option to context menu to reset the panel

---

mate-panel/panel-context-menu.c

Fix for https://github.com/mate-desktop/mate-panel/pull/655#issuecomment-332534233 , which is the danger of accidently resetting a panel and trashing  a user created layout

panel-context-menu: Add confirmation dialog to panel reset option

---

mate-panel/panel-widget.c

Stop panel from collapsing left on adding fish, moving window-list(or other wncklet applet) on otherwise empty panel. Stop collapse left of panel with one applet from wncklet(and no other applets) on adding 2nd applet from wncklet. 
Fixes https://github.com/mate-desktop/mate-panel/issues/661

Stop panel collapse left on adding certain out-of-process applets

---

applets/notification_area/status-notifier/sn-dbus-menu.c
applets/notification_area/status-notifier/sn-item.c

Mostly fixes serious mispositioning (on popup) of network-manager applet (indicator mode) menus when connections were changed on last showing of menu and applet is on bottom panel and especially on the bottom right. A slight low positioning on a bottom panel can remain when a connection is activated and a few menu items are added, thus expanding the menu while it is still showing.

GTK 3.22/status-notifer Fix menu position if size changed since last shown

---

applets/notification_area/status-notifier/sn-item-v0.c

Hide the mate-polkit statusnotifier icon (and only that icon) if it is set passive.  Works with https://github.com/mate-desktop/mate-polkit/pull/38 in mate-polkit to fix https://github.com/mate-desktop/mate-polkit/issues/35 (status notifier icon keeps showing after dropping elevated privileges). Keep the other passive indicators showing as they are too often needed.

status-notifier: hide mate-polkit icon if passive

---

applets/clock/clock-location-tile.c
applets/clock/clock.c
applets/notification_area/status-notifier/sn-item.c
mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c
mate-panel/panel-toplevel.c

Static code analysis using Cppcheck found these simple warnings (considered style warning) as well as a huge number of variables that could be reduced in scope and have been left alone as that would be a major job.

Fix some simple warnings found by Cppcheck

---

mate-panel/panel-toplevel.c

this commit fixes #682
When the resolution changes, at the same time refresh the location of the icon on the right.

Keep the right icons on bottom still displaying right when the resolution change larger. #682

---

applets/notification_area/status-notifier/sn-item-v0.c

Fix 1px wide invisible icon in cases such as
https://github.com/mate-desktop/mate-panel/issues/695
Show the "image-missing" icon if the named icon cannot be found or loaded

status-notifier: fix failure to show icon for missing icon

---

applets/notification_area/status-notifier/sn-item-v0.c

Fix  https://github.com/mate-desktop/mate-panel/issues/695 and similar failures to load icons when the application calls for a path and not an icon name

status-notifier: load icons specified by path

---

applets/notification_area/status-notifier/sn-host-v0.c

patch by https://github.com/supermaz to catch the no-items/NULL case returned by  sn_watcher_v0_gen_dup_registered_items (v0->watcher);

status-notifier: properly handle the NULL case for items

---

mate-panel/libmate-panel-applet-private/panel-applet-container.c
mate-panel/libmate-panel-applet-private/panel-applet-container.h
mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c

don't mess with additional references to a GCancellable, instead
keep just a const pointer to the internal operation data and use
it as a key when it's needed to cancel the operation.
fixes https://github.com/mate-desktop/mate-panel/issues/214
fixes https://github.com/mate-desktop/mate-panel/issues/431

rework the process of cancelling the background change operation

---

applets/wncklet/workspace-switcher.ui

Removed deprecated ui elements to make it fully compatible with GTK+ 3
and additionally made the dialog resizeable.

Update workspace switcher properties dialog

---

mate-panel/panel-applet-frame.c

how to test:
for example: `killall mate-sensors-applet` and see the focus without/with the PR

get focus when displaying "applet broken" dialog

---

mate-panel/panel-run-dialog.c

Fix https://github.com/mate-desktop/mate-panel/issues/706
patch by https://github.com/muesli4

panel-run-dialog: fix segfault when program list is enabled

---

applets/notification_area/status-notifier/sn-dbus-menu-item.c

Ensure only checked radio button is shown as checked, not all the radio buttons. Issue is apparently caused by a bug in gtk_radio_menu_item_new and also effects gnome-panel and Cinnamon. We can fix it here so radio buttons are actually usable in the status notifier.

Fix rendering of radio buttons in status notifier

---

applets/notification_area/status-notifier/sn-dbus-menu.c
applets/notification_area/status-notifier/sn-item-v0.c

Should address both crashes mentioned in https://github.com/mate-desktop/mate-panel/issues/686

status-notifier: fix crashes on wrong GVariant format

---

mate-panel/panel-menu-bar.c
mate-panel/panel-menu-button.c

do you like this icon? other icon? or with no icon?
without the PR:
with the PR:

set the "document-properties" icon in "Edit Menus"

---

mate-panel/panel-context-menu.c

I've decided to separate this menu item from the previous ones, even though it invokes a confirmation dialog now. Just thought that the radical actions should be in a separate section.
This is a follow-up to discussions in https://github.com/mate-desktop/mate-panel/pull/655, https://github.com/mate-desktop/mate-panel/pull/664, https://github.com/mate-desktop/mate-panel/pull/665.

context menu: add separator before Reset Panel menu item

---

mate-panel/panel-stock-icons.c

This is an alternative fix like the PR https://github.com/mate-desktop/mate-panel/pull/726, but without removing code

panel-stock-icons.c: Fix warnings in ~/.xsession-errors

---

mate-panel/panel-multiscreen.c
mate-panel/panel-run-dialog.c
mate-panel/panel-struts.c
mate-panel/panel-toplevel.c

This allows for supporting multiple monitors in HiDPI.
_Caveat_: I do _not_ own an external HiDPI monitor, so I use `xrandr` in the command line to set the scale and positioning of the second monitor.
@flexiondotorg - I think you're the only one here with both a HiDPI laptop _and_ a HiDPI external monitor. Could you test this, please?

Scale monitor geometries down to device pixels

---

applets/notification_area/system-tray/na-tray-child.c
applets/notification_area/system-tray/na-tray.c

Fix too wide spacing of tray icons when window-scaling-factor = 2 or more. Tested both in and out of process, and in both vertical and horizontal panels.

hidpi: fix tray icon spacing with window-scaling > 1

---

mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c

Fix https://github.com/mate-desktop/mate-panel/issues/758
Ensure that themes such as GNOME themes (e.g Adwaita) that do not explicitly support MATE show the drag handles for applets such as tray and window-list. Tuned for Adwaita and Adwaita-Dark

Theme: show applet handles on non-MATE themes

---

mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c

Special case the GNOME HighContrast and HighContrastInverse themes to give max contrast on tray and window list applet handles. Follow-on to https://github.com/mate-desktop/mate-panel/commit/2e0a74d9458480966f2a87d1d66a58552a873300

Accessibility: white/black applet handles in GNOME high contrast themes

---

mate-panel/libpanel-util/panel-gtk.c
mate-panel/libpanel-util/panel-gtk.h
mate-panel/menu.c
mate-panel/panel-context-menu.c

avoid deprecated:
gtk_image_menu_item_new_with_mnemonic
gtk_image_menu_item_set_image

panel-context-menu.c: avoid deprecated GtkImageMenuItem

---

mate-panel/panel-toplevel.c

Revert "panel-toplevel: Remove pointer boundary check in panel_toplevel queue_auto_hide()"
This reverts commit 0d29acf6a70090ee771de2793b1af8e1388a430f.
Which causes a regression.
Fixes https://github.com/mate-desktop/mate-panel/issues/773

fix menubar behaviour when using auto-hide

---

data/Makefile.am
data/mate-panel.css
data/panel-grid-symbolic.svg
mate-panel/Makefile.am
mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c
mate-panel/main.c

*Do NOT use border, as it is not overridden in MATE themes and pushes the image out of place
*Use two gradient images to make a 3x3 grid resembling MATE theme 3 holes image that works in both vertical and horizontal panels
*Note that while drag handle now shows in vertical panel, it only scales in horizontal panel as px and not % must be used in horizontal direction

Theme: consistant theming for applet drag handles in all themes

---

mate-panel/applet.c
mate-panel/libpanel-util/panel-gtk.c
mate-panel/libpanel-util/panel-gtk.h

avoid deprecated:
gtk_image_menu_item_new_with_mnemonic
gtk_image_menu_item_set_image
**EDIT:** this PR needs to work with https://github.com/mate-desktop/mate-themes/pull/219

applet.c: avoid deprecated GtkImageMenuItem

---

libmate-panel-applet/mate-panel-applet.c

Fix https://github.com/mate-desktop/mate-panel/issues/797 and https://github.com/mate-desktop/mate-panel/issues/799
Use  GTK_SIZE_REQUEST_CONSTANT_SIZE  rather than using height-for-width or width-for-height geometry management(https://wiki.gnome.org/HowDoI/CustomWidgets#What_virtual_functions_to_implement.3F)
as was recently done for on out-of-process applets to fix HiDPI wrong-size rendering. Note that disabling this only for the window list causes other in-process applets to disappear when the window list is present on a nonexpanded panel, and that adding and removing the other in-process applets is also made to work after a delay of about a second.

fix rendering and removal of in-process applets on unexpanded panel

---

applets/clock/clock-location-tile.c
applets/clock/clock.c
applets/wncklet/showdesktop.c
mate-panel/button-widget.c
mate-panel/button-widget.h
mate-panel/launcher.c
mate-panel/panel-util.c
mate-panel/panel-util.h
mate-panel/xstuff.c
mate-panel/xstuff.h

This improves support for HiDPI by loading properly scaled surfaces for
launcher and drawer icons.
It also fixes the Show Desktop wncklet to show a surface icon. Other
wncklets have their icons determined by libwnck, so they remain as
pixbufs.
Fixes mate-desktop/mate-desktop/issues/314

Convert launcher icons to cairo surfaces

---

data/theme/mate-panel.css
mate-panel/libpanel-util/panel-gtk.c

Most panel menus excluding main menus. Duplicate behavior of now-deprecated code replaced by github.com/mate-desktop/mate-panel/commit/86701517e7d7cb3d2c08a40d76af97308f18902c

Load menu icons only when "menus-have-icons" is set

---

data/theme/mate-panel.css
mate-panel/libpanel-util/panel-gtk.c
mate-panel/menu.c
mate-panel/panel-context-menu.c

Fixes https://github.com/mate-desktop/mate-panel/pull/820#issuecomment-399709389

menu.c: Fix: Keep spaces in the left if "menus-have-icons" is off

---

mate-panel/panel-toplevel.c

This makes it possible to add theme settings for fixing 
https://github.com/mate-desktop/mate-panel/issues/617
https://github.com/mate-desktop/mate-panel/issues/344
https://github.com/mate-desktop/mate-panel/issues/193
An example css for Menta and other light themes which can be used in
~.config/gtk-3.0/gtk.css
```
.mate-panel-menu-bar.horizontal.top > grid {
border-style: outset;
border-width: 0px 0px 1px 0px;
border-color: rgba(0, 0, 0, 0.23);
}
.mate-panel-menu-bar.horizontal.bottom > grid {
border-style: outset;
border-width: 1px 0px 0px 0px;
border-color: rgba(0, 0, 0, 0.23);
}
.mate-panel-menu-bar.vertical.left > grid {
border-style: outset;
border-width: 0px 1px 0px 0px;
border-color: rgba(0, 0, 0, 0.23);
}
.mate-panel-menu-bar.vertical.right > grid {
border-style: outset; …
```

panel-toplevel: add position css class

---

mate-panel/panel-menu-button.c

panel-menu-button: replace deprecated gtk_menu_popup

---

applets/notification_area/system-tray/na-tray-child.c

Remove explicit width/height setting and GTK2 leftovers that may be responsible for cutting tray icons vertically.
Possible fix for https://github.com/mate-desktop/mate-panel/issues/746
will test in the laptop which often has this problem

Fix tray icon cutting

---

mate-panel/applet.c
mate-panel/panel-action-protocol.c
mate-panel/panel.c

There is one occurrence of `gtk_menu_popup` left in menu.c, but replacing it make problems with that context-menu inside the the menu of menubar and main-menu.
Please test.

replace deprecated gtk_menu_popup

---

applets/notification_area/system-tray/na-tray-child.c

Prevent most corruption of tray icons and reduce by half incomplete rendering of them, replace a never-built code block that could not be built, and replace (deprecated) direct expose handling with gtk_widget_hide/gtk_widget_show_all
Note that this is needed for GTK 3.23 but may help remaining icon issues with GTK 3.22 as well and is simpler code in any case.

Tray: simplify force-redraw, use code that actually works

---

libmate-panel-applet/mate-panel-applet.c

Limit workaround for GTK 3.22 double width/height allocation to GTK 3.22 builds only. Fix https://github.com/mate-desktop/mate-panel/issues/843 in which out-of-process applets get only half their needed width with window-scaling=2. This issue is caused by
https://github.com/mate-desktop/mate-panel/commit/ff04f332136272a14c588da3f2d582ba0ff01be1
which is a fix for for out-of-process applets getting double their needed width. A bug in GTK 3.22 caused that and is fixed in GTK 3.23

GTK 3.23: fix applet size allocation

---

libmate-panel-applet/mate-panel-applet.c

This is for the tray: GtkPlug/GtkSocket widgets are used to embed tray icons (GtkStatusIcons) in the tray even if the tray is in-process and does not use the plug/socket widgets to be itself embedded in the panel.

mate-panel-applet: setup_x_error_handler for in-process applets too

---

applets/notification_area/Makefile.am
applets/notification_area/main.c
applets/notification_area/main.h
applets/notification_area/na-grid.c
applets/notification_area/na-grid.h
applets/notification_area/na.gresource.xml
applets/notification_area/notification-area-menu.xml
applets/notification_area/notification-area-preferences-dialog.ui
applets/notification_area/org.mate.panel.applet.notification-area.gschema.xml.in
applets/notification_area/testtray.c
configure.ac
mate-panel/button-widget.c
po/POTFILES.in

This takes care of some issues from https://github.com/mate-desktop/mate-panel/issues/157
And it's a final remake of the own issue I had created: https://github.com/mate-desktop/mate-panel/pull/325 (at the time mate-panel was being ported to Gtk3 so it was messy, now that it's finally only Gtk3, I've made the proper changes)
This change limits the size taken by all BUTTON_WIDGETs when the panel is wide, because for the moment when for example the panel is horizontal 200 pixels wide/high, the widgets take up 200x200 for an icon of max size 48.
I've set it to take now (for this example) 50x200 or 200x50 (if it's a vertical panel 200px wide)
If users want to leave the same space as before around the icons they just have to move them on the panel anyway and leave empty space around and it can …

Fix on wide panels (vert/horz)

---

mate-panel/panel-action-protocol.c

Fix regression introduced by https://github.com/mate-desktop/mate-panel/commit/17ac8aab4d139cb917619a3a981300f51b750c17 and ensure that menu shown follows same theme as menu shown from panel menu button or panel menu bar.

Ensure alt-F1 can show the menu even if no menu applet on panel

---

mate-panel/panel-menu-bar.c
mate-panel/panel-menu-button.c
mate-panel/panel-util.c
mate-panel/panel-util.h

menu-bar: transfer focus correctly on alt-F1
The background is in https://gitlab.gnome.org/GNOME/gtk/issues/85 . One of the conclusions, in https://gitlab.gnome.org/GNOME/gtk/issues/85#note_264804, is that mate-panel needs to properly transfer focus on alt-F1 keyboard shortcut.
It used to work only by luck before, only because gtk used to deactivate itself during a keyboard grab. But as discussed in https://gitlab.gnome.org/GNOME/gtk/issues/85 that behavior poses accessibility feedback issues, is not coherent, and keyboard grab feedback will not be available in wayland anyway. Thus @ebassi saying in https://gitlab.gnome.org/GNOME/gtk/issues/85#note_264804 that not transferring focus properly is the actual bug.
This change explictly switches to the menu bar after saving which X Window had …

Backport #863 (Alt+F1 focus fix) to 1.20

---

applets/notification_area/notification-area-preferences-dialog.ui

We have the deprecated property in that ui file since the PR https://github.com/mate-desktop/mate-panel/pull/856

notification-area-preferences-dialog.ui: avoid GtkButton:use-stock

---

configure.ac

This was a suggested change to my Wayland PR, but since I just got it from prexisting code, I thought it would be best to propose it separately.
Original comment by @muktupavels:
> Well it is 2018... I would just require pkg-config file and would remove old-style detection...
https://gitlab.freedesktop.org/xorg/lib/libx11
https://gitlab.freedesktop.org/xorg/lib/libxau
This tells that x11.pc and xau.pc is available as minimum for 9 years.

Remove legacy X11 package detection

---

mate-panel/wayland-protocols/wlr-layer-shell-unstable-v1.xml
mate-panel/wayland-protocols/xdg-shell.xml

This adds the xml Wayland protocols from which we can use `wayland-scanner` to generate libwayland interface code at build time. A future PR will add the make files necessary to generate the code. This will be used by the upcoming Wayland backend you can find in #873. This is an alternative to committing the generated code, as I was doing in #895.

Add XML Wayland protocols

---

applets/clock/clock.c

This function is no longer needed to make the clock fit in any panel, and no longer seems to affect warnings given in terminal with a debug build of GTK 3.24. Not forcing zero padding allows themers more control, and retaining the clock-applet-button widget name allows themers to keep any unwanted padding off the clockbox. Tested with all themes

clock.c: Force negative margin, not padding on clockbutton 

---

applets/clock/clock.c

fixes weather-icon problems with some themes
with TOK theme:
with adwaita:
Sorry, i can't test linuxmint themes, because it isn't allowed to spam my mate-appearance-properties with tons of similar themes.
@monsta @lukefromdc 
Does this work for you?

clock: force_no_button_vertical_padding

---

applets/notification_area/na-grid.c

Note that vertical and horizontal panels require different options in the grid, as "homogenous" is needed in rows for horizontal panels and columns in vertical panels to prevent icon rendering problems including icons growing without limit when the tray is moved from a horizontal to a vertical panel

Tray: Fix too-wide icon spacing after mate-polkit has been used and icon dismissed (privileges dropped) with  sni

---

applets/clock/clock.c

Connect to the "change_size" signal and reload the icon at the correct size

Clock: ensure weather icon size is correct for panel height

---

applets/clock/clock.c

For some reasons padding settings for `button` widget in gtk+  themes are still ignored if clock-applet is build-in-process.
Forcing a horizontal padding is to make sure we have space left and right from the button.
I think it looks better to have a space there.
`padding-left/right: 4 px;` is used by our and gtk+ default themes. So this is a good value.

clock: set  horizontal padding for clock-button

---

applets/notification_area/Makefile.am
applets/notification_area/main.c
applets/notification_area/na-grid.c
applets/notification_area/na-grid.h
applets/notification_area/testtray.c
mate-panel/button-widget.c

This is a simple cherry-pick of GtkGrid port in master branch and fixes https://github.com/mate-desktop/mate-panel/issues/907
For reproducing the issue you need to use MATE 1.20.x and follow instructions from report.
With master branch all works well.
Use the script with the `yad` command.
Without the PR you will see a broken na-tray applet with high cpu load.
Note, you need to kill all `yad` processes before reloading the panel.
With the PR you will see 30 instances of `yad` UI in na-tray applet without increasing the cpu load.

Na-tray-applet high cpu load fix for 1.20

---

mate-panel/panel-action-protocol.c
mate-panel/panel-action-protocol.h
mate-panel/panel-force-quit.c
mate-panel/panel-force-quit.h
mate-panel/panel-xutils.c
mate-panel/panel-xutils.h
mate-panel/xstuff.c
mate-panel/xstuff.h

Add various compile time and runtime checks to keep X11 specific files running on Wayland.

Check X11 support before using X11 specific features

---

applets/notification_area/main.c
applets/notification_area/na-grid.c

*clear applet gsettings on dispose to stop crash and memory leak introduced in github.com/mate-desktop/mate-panel/commit/10b9c30fc79de5f8d9516ba153df233c4968da65
*tray: fix misplaced g_return_if_fail check

fix crash on removing tray

---

mate-panel/panel-menu-button.c

Ensure that on a vertical panel, if the menubutton is at the top of the panel, align the menu with the top screen edge or if a top panel is also present the bottom edge of that top panel(as set by struts).
Ensure that on a vertical panel, if the menubutton is at the bottom of the panel, align the menu with the bottom screen edge or if a bottom panel is also present the top edge of that top panel(as set by struts).
```
Setting 
GDK_GRAVITY_SOUTH_WEST,
GDK_GRAVITY_NORTH_WEST,
```
for the menu button popup menu seems to allow the default anchor hints
`GDK_ANCHOR_FLIP_X | GDK_ANCHOR_FLIP_Y | GDK_ANCHOR_SLIDE_X | GDK_ANCHOR_SLIDE_Y | GDK_ANCHOR_RESIZE_X | GDK_ANCHOR_RESIZE_Y`
to automatically and correctly set up the menu positions
See …

Properly align button menu positions on vertical panels

---

.travis.yml

This can fix #933 build fail on travis. The build log is here: https://travis-ci.org/mate-desktop/mate-panel/builds/493723076

Use docker-build on the master branch

---

mate-panel/panel-toplevel.c

Instead of filling in 4 `int`s, it now fills in a `GdkRectangle`. This is more readable and less error prone. (I'm working with this code from Wayland support, which is why it matters to me)

Change panel_toplevel_get_monitor_geometry signature

---

mate-panel/Makefile.am
mate-panel/applet.c
mate-panel/drawer.c
mate-panel/launcher.c
mate-panel/main.c
mate-panel/panel-background.c

Actual Wayland support still isn't here, this is just to get things organized in preparation. I also dropped a few seemingly unneeded X11 includes.

Don't build X11 files unless X11 is enabled

---

applets/notification_area/system-tray/na-tray-child.c

please, don't push to the 1.22 release

na-tray-child: avoid deprecated 'gtk_widget_set_double_buffered'

---

mate-panel/libpanel-util/panel-keyfile.c

Fixes Clang static analyzer warning:
warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119

[Security] panel-keyfile: Use 'g_strlcpy' instead of 'strcpy'

---

mate-panel/Makefile.am
mate-panel/wayland-protocols/Makefile.am

They're already in the `wayland-protocols` directory, so `-protocol` is just noise. I was the one who originally put it there, and this commit to fix it has been sitting around my branches for a while.

Dropped *-protocol suffix from generated files

---

mate-panel/panel-layout.c

This allows the user to add panels and applets if no `default.layout` is found

Create empty panel on first launch if no default layout is found

---

libmate-panel-applet/mate-panel-applet.c

Do not open the context menu on tab-or on anything but the menu key. Note that Return must be used by some applets (e.g. the clock) for something else. Fixes https://github.com/mate-desktop/mate-panel/issues/952

Fix panel applet keyboard focus trap

---

applets/wncklet/Makefile.am
applets/wncklet/org.mate.panel.applet.window-list-previews.gschema.xml.in
applets/wncklet/org.mate.panel.applet.window-list.gschema.xml.in
applets/wncklet/window-list.c
applets/wncklet/window-list.ui
configure.ac

Note: This feature requires `libwnck` version [3.32.0](https://gitlab.gnome.org/GNOME/libwnck/commit/d3a714db6af5c1a146effb8d8f827b8973bbb91c) or higher.
When hovering on taskbar entries, display a popup with a thumbnail
of the associated window. Popup goes away when leaving the button.
If a window has not been mapped since the applet started, it will
not display a thumbnail. Once mapped, however, it will use its
latest available thumbnail as preview, even when minimized.
Fixes #391

window-list: Show window previews on hover

---

mate-panel/button-widget.c
mate-panel/panel-toplevel.c

Fixes `cppcheck` warnings:
```
[mate-panel/button-widget.c:180]: (style) Clarify calculation precedence for '&' and '?'.
[mate-panel/button-widget.c:181]: (style) Clarify calculation precedence for '&' and '?'.
[mate-panel/button-widget.c:315]: (style) Clarify calculation precedence for '&' and '?'.
[mate-panel/panel-toplevel.c:2315]: (style) Clarify calculation precedence for '&' and '?'.
[mate-panel/panel-toplevel.c:4687]: (style) Clarify calculation precedence for '&' and '?'.
[mate-panel/panel-toplevel.c:5036]: (style) Clarify calculation precedence for '&' and '?'.
```
https://en.cppreference.com/w/c/language/operator_precedence

Clarify calculation precedence for '&' and '?'

---

applets/clock/clock.gresource.xml
mate-panel/panel.gresource.xml

shrink the size of binary files:
```shell
$ ./autogen.sh --prefix=/usr && make && LANG=C ls -la applets/clock/.libs/clock-applet
-rwxrwxr-x. 1 robert robert 748592 May  8 11:47 applets/clock/.libs/clock-applet
$ make distclean
$ git checkout dd161527f822ab152ee97c4ff8f4e111da10d27f
$ ./autogen.sh --prefix=/usr && make && LANG=C ls -la applets/clock/.libs/clock-applet
-rwxrwxr-x. 1 robert robert 818232 May  8 12:25 applets/clock/.libs/clock-applet
```

Set compressed="true" for gresource text files

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/button-widget.c
mate-panel/libmate-panel-applet-private/panel-applet-container.c
mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c
mate-panel/libmate-panel-applet-private/panel-applets-manager-dbus.c
mate-panel/libpanel-util/panel-icon-chooser.c
mate-panel/panel-action-button.c
mate-panel/panel-applet-frame.c
mate-panel/panel-ditem-editor.c
mate-panel/panel-menu-bar.c
mate-panel/panel-menu-button.c
mate-panel/panel-menu-items.c
mate-panel/panel-separator.c
mate-panel/panel-toplevel.c

Avoid deprecated g_type_class_add_private under `libmate-panel-applet` and `mate-panel` directories.

Avoid deprecated g_type_class_add_private

---

mate-panel/panel-profile.c
mate-panel/panel-toplevel.c

Fixes https://github.com/mate-desktop/mate-panel/issues/436
How to test:
1. Resetting the panel layout
- use `mate-panel --reset` to reset the panel(s) to the current default layout
- use `mate-panel --reset --layout=<layout_name>` to set the new default layout and reset the panel(s) to it
- the panel should not crash
- the panel should reappear with the default layout
2. Deleting one panel in a multi-panel layout
- use "Delete this panel" menu item from the right-click menu to delete that panel
- the panel should not crash (https://github.com/mate-desktop/mate-panel/issues/65 should not happen again)
Both problems I've described in https://github.com/mate-desktop/mate-panel/issues/436#issuecomment-491845638 can be more often reproduced in Ubuntu than in Debian Testing, for example. …

fix panel reset problems

---

mate-panel/libmate-panel-applet-private/panel-applets-manager-dbus.c

This adds an environment variable (`MATE_PANEL_APPLET_LIB_PREFIX`) that if set, will be used when searching for applet libraries. This is required for packaging the panel in a snap, as I'm doing in https://github.com/wmww/mate-wayland-snap

Add MATE_PANEL_APPLET_LIB_PREFIX environment variable

---

libmate-panel-applet/Makefile.am

Currently installing mate-panel fails with the error
/bin/mkdir -p '/usr/share/gir-1.0'
/usr/bin/install -c -m 644 MatePanelApplet-4.0.gir '/usr/share/gir-1.0'
/usr/bin/install: cannot create regular file '/usr/share/gir-1.0/MatePanelApplet-4.0.gir': Permission denied
when configure is called with the --prefix option.
This fix is the same used in:
* caja (libcaja-extension/Makefile.am)
* eom (src/Makefile.am)
* libmatekbd (libmatekbd/Makefile.am)
* mate-desktop (libmate-desktop/Makefile.am)
* pluma (pluma/Makefile.am)

Fix Makefile.am to install in a given prefix path

---

mate-panel/Makefile.am
mate-panel/panel-background-monitor.c
mate-panel/panel-background-monitor.h
mate-panel/panel-background.c
mate-panel/panel-background.h

`PanelBackgroundMonitor` pulls the desktop background out of the root window for in-process compositing. This is both impossible and unneeded on Wayland, so I made the files X11-only. Unfortunately the desktop pixmap (`PanelBackground->desktop`) was previously retrieved even when it was not needed, so I had to shuffle some logic around a bit to make that happen only on X11.

Get panel background ready for Wayland

---

mate-panel/Makefile.am
mate-panel/launcher.c
mate-panel/main.c
mate-panel/panel-multimonitor.c
mate-panel/panel-multimonitor.h
mate-panel/panel-profile.c
mate-panel/panel-recent.c
mate-panel/panel-run-dialog.c
mate-panel/panel-struts.c
mate-panel/panel-toplevel.c
mate-panel/panel.c

Since GTK 3.10 (older than our current required version of 3.22) GTK has not supported multiple screens. In panel-multiscreen.c, `screens = 1` was hard coded, but the logic to handle multiple screens was still laying around. This renames panel-multiscreen to panel-multimonitor, and removes all logic dealing with screens from it. I needed this for Wayland, but It is also a step toward GTK4 (where `GdkScreen` doesn't exist).
There is still some logic around RANDR in panel-multimonitor that I think is left over from times long past, but that can be dealt with another time by someone else.

Panel multiscreen -> panel multimonitor

---

mate-panel/panel-multimonitor.c
mate-panel/panel-multimonitor.h
mate-panel/panel-toplevel.c

On top of #988
Use size and position of monitors instead of dimensions of the `GdkScreen`. `GdkScreen` Doesn't make sense in Wayland, and is going away in GTK4.

Panel toplevel use monitors instead of GdkScreen size

---

configure.ac
mate-panel/Makefile.am
mate-panel/main.c
mate-panel/panel-toplevel.c
mate-panel/wayland-backend.c
mate-panel/wayland-backend.h

This is the PR we've all been waiting for. The one that finally adds full Wayland support to the panel. You can test this without even building from source (see the Mir section of 'To run')
Based on ~#983~, ~#984~, ~#985~, ~#986~, ~#988~, ~#989~, ~#990~ 
You'll need to compile and install [GTK Layer Shell](https://github.com/wmww/gtk-layer-shell). After that run `./autogen.sh --with-in-process-applets=all --enable-wayland --enable-x11` and make and install. Installing is required if the build that is currently installed did not have `--with-in-process-applets=all`. If you don't install it will try to use out-of-process applets, which fail on Wayland.
First, you'll need a Wayland compositor that supports Layer Shell.
* Wlroots based compositors
* On sway the basics work, but popups don't …

Wayland support

---

libmate-panel-applet/mate-panel-applet.c
mate-panel/panel-menu-button.c

This PR effects right-click menus on applets and opening the application menu.
On X, it appears the X struts we create automatically push the menus off the panel. The same does not happen on Wayland, so popups cover up the panel. This fixes the two cases where this is definitely bad, by adjusting the anchors so the popups appear in the right place. This should not change behavior on X (the X server will just no longer need to shove popups out of the way).
There are still cases where on X popups appear off the panel and on Wayland over top of it (ex right clicking on the empty space on the panel). However, the remaining cases use `gtk_menu_popup_at_pointer ()`. IMO this looks fine and is arguably preferable behavior in those cases to what X does.

Fix popup placement on Wayland

---

mate-panel/Makefile.am
mate-panel/wayland-backend.c

Whoops. If you're testing, take the opertunity to update to the newest GTK Layer Shell as well, which has switched from autotools to Meson.

Fix GTK Layer Shell include and CFLAGS

---

mate-panel/panel-toplevel.c

This fixes https://github.com/mate-desktop/mate-panel/issues/745.
A regression from https://github.com/mate-desktop/mate-panel/pull/683 caused all applets on expanded vertical panel stick to the top. In addition it made window list (if it's present on that panel) completely disappear...
For testing I've used a horizontal panel with some applet(s) set to stay on the right (tray area or workspace switcher). Then I've moved that panel to the left, making it vertical. Without this fix, all applets were stuck to the top. With this fix, tray area or workspace switcher stay at panel's bottom.

Fix applets placement on expanded vertical panel

---

mate-panel/panel-layout.c

If the layout name begins with a '/', load from that filename instead of
from PANEL_LAYOUTS_DIR.  This allows loading of layouts from home
directories and other write-permitted locations.

Load layouts from absolute paths

---

mate-panel/panel-addto.c

The "Main Menu" becomes "Compact Menu", since it is indeed the most compact menu available for MATE.
The "Menu Bar" becomes "Classic Menu" since this is what most users identify as the classic menu used in GNOME2/MATE. The description more clearly articulates the menu features.

Change the panel menu descriptions to better identify them

---

applets/notification_area/main.c

This is better for HIDPI resolution with larger icons.
And tray- applet can be displayed in in one row with
a full-size top/bottom panel.
Please test.

na-tray: increase min_icon_size value

---

applets/notification_area/status-notifier/sn-dbus-menu-item.c
applets/notification_area/status-notifier/sn-item-v0.c

Instead of GdkPixbuf, so that SNI icons can render correctly on HiDPI
displays.

status-notifier: Render icons as cairo surface

---

applets/clock/clock.c

This adds the current displayed time from clock applet to its widget's ATK attributes. When using Orca's mouse review this makes the applet tell something usefull.

Add clock ATK name

---

applets/clock/clock.c

The clock format was fixed in https://github.com/mate-desktop/mate-panel/commit/4d20a0003798eea253fed6ea8f02cec5da6ffb2d, but it only needed fixing when LC_TIME and LANGUAGE are different.
In the code introduced by this commit `env_language != env_lc_time` doesn't properly compare the strings. It compares the pointers, and thus it always returns TRUE.
This fixes the comparison so the actual values of the strings are compared and we don't apply the format fix when we don't need to.
The comparison was also duplicated in the original code, it's factorized here into a `use_lctime` variable.
Ref: https://github.com/linuxmint/cinnamon-desktop/pull/142.

Clock applet: Fix string comparison

---

mate-panel/panel-toplevel.c

Do not set an extra a11y name and description on an internal child of the panel, because its toplevel has most of it already through setting the GTK window title.  Instead, explicitly set the a11y name and description on the toplevel directly, possibly overriding GTK's value implicitly set via `gtk_window_set_title()`, but which would be the same anyway.
This prevents e.g. a screen reader vocalizing the panel name twice when entering it, once for the toplevel and once for the internal child.
This also avoids announcing the panel again when moving from one of the hide buttons to one of the applets or launcher.
---
To test, you can:
* See in Accerciser that now the panels don't have the same name on their toplevel and its 3rd child (`0 0 0` path under it in Accerciser's parlance)
* With …

Avoid double a11y description on panel toplevels

---

configure.ac

```shell
$ ./autogen.sh --enable-compile-warnings=maximum  --enable-debug
<cut>
mate-panel 1.23.3
=================
prefix:                        /usr/local
exec_prefix:                   ${prefix}
libdir:                        ${exec_prefix}/lib
bindir:                        ${exec_prefix}/bin
sbindir:                       ${exec_prefix}/sbin
sysconfdir:                    ${prefix}/etc
localstatedir:                 ${prefix}/var
datadir:                       ${datarootdir}
source code location:          .
compiler:                      gcc
cflags:                         -g -O0
Maintainer mode:               yes
Use *_DISABLE_DEPRECATED:      no
Applets to build in-process:   (none)
Wayland support:               yes
X11 support:                   yes
XRandr support: …
```

build: show warning flags on configure summary

---

mate-panel/panel-background.c
mate-panel/panel-layout.c

```
panel-background.c:77:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
77 | panel_background_prepare_css ()
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
panel-layout.c:97:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
97 | panel_layout_filename ()
| ^~~~~~~~~~~~~~~~~~~~~
```

Remove warnings: function declaration isn’t a prototype

---

mate-panel/button-widget.c

Test: hover color mask on buttons panel.
```
Indirect leak of 4320 byte(s) in 3 object(s) allocated from:
#0 0x7f0dae0e6c58 in __interceptor_malloc (/lib64/libasan.so.5+0x10dc58)
#1 0x7f0dad440fff  (/lib64/libcairo.so.2+0x2afff)
#2 0x4378ed in button_widget_reload_surface /home/robert/sanitizer/mate-panel/mate-panel/button-widget.c:195
#3 0x439cb0 in button_widget_size_allocate /home/robert/sanitizer/mate-panel/mate-panel/button-widget.c:529
#4 0x7f0dad162647 in g_closure_invoke (/lib64/libgobject-2.0.so.0+0x13647)
```

button-widget: Fix memory leak

---

applets/wncklet/window-list.c
applets/wncklet/window-list.ui

Before:
After:
Additionally the GtkSpinButton is now insensitive when preview is disabled.

preferences dialog: change show thumbnails radio to check button

---

.travis.yml

We need pygithub-1.43.8+ to release tarballs into github release page and mate release server, but python3-github on ubuntu 18.04(Travis CI) is 1.26.0, so we must use pip to install the latest version of pygithub.

fix release tarballs on travis CI failed

---

mate-panel/panel-util.c

When building with `--disable-x11` (Wayland-only) one X11-related header appears to be included outside of `#ifdef HAVE_X11`. However, Gtk+ 3 only installs the header if built with `--enable-x11-backend`.

panel-util: avoid X11-specific header

---

mate-panel/panel-applet-frame.c
mate-panel/panel-frame.c
mate-panel/panel-profile.c
mate-panel/panel-toplevel.c
mate-panel/panel-util.c

A bunch of tiny fixes found by valgrind.
Please test if this fixes #1085

Memory leak fixes

---

mate-panel/panel-context-menu.c

Change "Reset Panel" to "Reset all Panels" in context mnenu and in reset confirmation dialog to make clear that ALL panels will be reset. Closes https://github.com/mate-desktop/mate-panel/issues/955

Clarify meaning of panel reset option

---

applets/clock/clock-location-tile.c
applets/clock/clock-location.c
applets/clock/clock-utils.c
applets/clock/clock.c
applets/clock/set-timezone.c
applets/wncklet/showdesktop.c
applets/wncklet/workspace-switcher.c
libmate-panel-applet/mate-panel-applet.c
mate-panel/launcher.c
mate-panel/panel-lockdown.c
mate-panel/panel-menu-items.c
mate-panel/panel-profile.c
mate-panel/panel-properties-dialog.c
mate-panel/panel-run-dialog.c

Another bunch of memleak fixes found by compiling applets in-process. The fixes from #1112 are not included in this branch.
I'm still seeing increasing memory consumption about 1MB an hour but nothing dramatic otherwise.

Memory leak fixes pt. 2

---

applets/clock/clock.c

```
clock.c:1180:14: warning: assignment to 'GSList *' {aka 'struct _GSList *'} from incompatible pointer type 'GList *' {aka 'struct _GList *'} [-Wincompatible-pointer-types]
1180 |         node = g_list_copy (cities);
|              ^
clock.c:1181:29: warning: passing argument 1 of 'g_list_sort' from incompatible pointer type [-Wincompatible-pointer-types]
1181 |         node = g_list_sort (node, sort_locations_by_time_reverse_and_name);
|                             ^~~~
|                             |
|                             GSList * {aka struct _GSList *}
```

clock: assignment to 'GSList *' from incompatible pointer type 'GList *'

---

mate-panel/panel-profile.c

When creating a new launcher, we try and find an available object ID by browsing the existing ones.  This however fails to take into account objects that were created but that didn't make it to the backend yet, leading to likely re-using the same ID when creating several objects roughly at the same time.  This happens e.g. when dropping several URIs together.
Drag 2 or more **non-image** files from Caja over to a panel.
Only one launcher gets created for the the last URI.
A launcher gets created for each URI.

Fix creating several launchers at once

---

mate-panel/panel.c

Instead of unconditionally setting the panel's background when an image file URI gets dropped on a panel, ask the user whether to create a launcher for that URI (like for non-image URIs) or to use the image as the panel's background.
A number of users have seen their panel's background changed unexpectedly due to unwanted drop of an image file over the panel, sometimes seeing this as a panel's bug (I personally know 2, at least a couple others have popped here and there).
Also, this behavior is inconsistent with dropping a URI pointing to any other type of file, where it would create a launcher for it.
Consequently, and as setting the panel's background doesn't seem like a so common task it ought to be super fast, ask the user what to do when receiving an image URI drop.
Also, when a drop …

Ask the user what to do when receiving an image drop

---

applets/wncklet/window-list.c

When a window is not visible we cannot capture its thumbnail. We used to
store the thumbnail when a window was visible so that we could reuse it
when minimized, but this can cause visual glitches.
Fixes #1127

wncklet: Hide window preview on non-visible windows

---

mate-panel/panel-toplevel.c

```
panel-toplevel.c: In function 'panel_toplevel_get_orientation':
/usr/include/glib-2.0/glib/gmessages.h:644:16: warning: implicit conversion from 'enum <anonymous>' to 'PanelOrientation' [-Wenum-conversion]
644 |         return (val); \
|                ^
panel-toplevel.c:5066:2: note: in expansion of macro 'g_return_val_if_fail'
5066 |  g_return_val_if_fail (PANEL_IS_TOPLEVEL (toplevel), GTK_ORIENTATION_HORIZONTAL);
|  ^~~~~~~~~~~~~~~~~~~~
```

panel-toplevel: Fix -Wenum-conversion warning

---

.build.yml
configure.ac

It appears this is no longer being used (if it ever was)

Drop 'xau' from PKG_CHECK_MODULES call

---

mate-panel/main.c

When I originally wrote this I wasn't aware of `gdk_set_allowed_backends ()`. We should use it instead of manually checking.

Use gdk_set_allowed_backends () instead of custom check

---

doc/reference/mate-panel-applet/Makefile.am

Fix make distcheck failed on archlinux:
```
make[2]: Leaving directory '/rootdir/mate-panel-1.25.1/_build/sub'
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
ERROR: files left in build directory after distclean:
./doc/reference/mate-panel-applet/mate-panel-applet.actions
make[1]: *** [Makefile:826: distcleancheck] Error 1
make[1]: Leaving directory '/rootdir/mate-panel-1.25.1/_build/sub'
make: *** [Makefile:755: distcheck] Error 1
!!! ERROR: run command [docker exec -t mate-panel-archlinux-build /rootdir/after_scripts].
```

travis: fix make distcheck error on archlinux

---

applets/wncklet/Makefile.am

```
applets/wncklet/Makefile.am:32: warning: source file 'wayland-protocol/wlr-foreign-toplevel-management-unstable-v1-code.c' is in a subdirectory,
applets/wncklet/Makefile.am:32: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your …
```

configure: remove warning about option 'subdir-objects' is disabled

---

applets/wncklet/wayland-backend.c

```
wayland-backend.c:58:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
58 | static TasklistManager *tasklist_manager_new ();
| ^~~~~~
--
wayland-backend.c:95:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
95 | wayland_tasklist_init_if_needed ()
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
wayland-backend.c:168:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
168 | tasklist_manager_new ()
| ^~~~~~~~~~~~~~~~~~~~
```

wncklet: function declaration isn't a prototype

---

mate-panel/Makefile.am
mate-panel/button-widget.c
mate-panel/panel-profile.c
mate-panel/panel-profile.h
mate-panel/panel-properties-dialog.c

- Enable the compositor
- Open panel properties dialog
- Set the panel background to solid color and enable color transparency.
- Close panel properties dialog
- Disable the compositor
- Open panel properties dialog

Fix solid color controls after disabling compositor

---

applets/wncklet/window-list.c

This allows thumbnail previews to be properly rendered on HiDPI displays
and ensures that the window surface is flushed before painting it.
Fixes #1166

window-list: Render thumbnails as cairo surfaces

---

applets/clock/clock.c
applets/fish/fish.c
applets/wncklet/showdesktop.c
applets/wncklet/window-list.c
applets/wncklet/window-menu.c
applets/wncklet/workspace-switcher.c
libmate-panel-applet/mate-panel-applet.h

This function has an empty body, so removing it should be fine. I tested all affected applets, they work as before for me.
Should not be merged before https://github.com/mate-desktop/mate-media/pull/170 and https://github.com/mate-desktop/mate-applets/pull/555.

remove dead function mate_panel_applet_set_background_widget

---

applets/fish/fish.c
applets/notification_area/main.c
applets/wncklet/workspace-switcher.c
mate-panel/panel-properties-dialog.c

```C
/**
* GtkSpinButton::value-changed:
* @spin_button: the object on which the signal was emitted
*
* The ::value-changed signal is emitted when the value represented by
* @spinbutton changes. Also see the #GtkSpinButton::output signal.
*/
spinbutton_signals[VALUE_CHANGED] =
g_signal_new (I_("value-changed"),
G_TYPE_FROM_CLASS (gobject_class),
G_SIGNAL_RUN_LAST,
G_STRUCT_OFFSET (GtkSpinButtonClass, value_changed),
NULL, NULL,
NULL,
G_TYPE_NONE, 0);
```
https://github.com/GNOME/gtk/blob/daa5d5aeadbebd2d1e764e953b8b6f0d21fbfacf/gtk/gtkspinbutton.c#L493-L507

Signal name is 'value-changed' for GtkSpinButton

---

applets/wncklet/window-list.c

culprit https://github.com/mate-desktop/mate-panel/commit/eda5735ce6b52e8cf738077027581bfe2257c3cb

wncklet: missing breaks on switch cases

---

applets/wncklet/workspace-switcher.c

```
applets/wncklet/workspace-switcher.c:378:11: style: Variable 'index' is assigned a value that is never used. [unreadVariable]
index += n_columns;
^
applets/wncklet/workspace-switcher.c:382:11: style: Variable 'index' is assigned a value that is never used. [unreadVariable]
index = 0;
^
applets/wncklet/workspace-switcher.c:386:11: style: Variable 'index' is assigned a value that is never used. [unreadVariable]
index = (index % n_columns) + 1;
^
applets/wncklet/workspace-switcher.c:393:10: style: Variable 'index' is assigned a value that is never used. [unreadVariable]
index++;
^
applets/wncklet/workspace-switcher.c:397:18: style: Variable 'index' is assigned a value that is never used. [unreadVariable]
index = 0;
^
applets/wncklet/workspace-switcher.c:416:11: style: Variable 'index' is …
```

wncklet: unread variable warning reported by cppcheck

---

applets/wncklet/workspace-switcher.c

```
applets/wncklet/workspace-switcher.c:212:6: style: Condition '!wm_name' is always true [knownConditionTrueFalse]
if (!wm_name)
^
```

wncklet: condition is always true warning reported by cppcheck

---

mate-panel/panel-properties-dialog.c

warning reported by cppcheck
```
mate-panel/panel-properties-dialog.c:941:9: style: Variable 'dialog' is assigned a value that is never used. [unreadVariable]
dialog = panel_properties_dialog_new (toplevel, gui);
^
```

panel-properties-dialog: show dialog on _present instead of _new

---

mate-panel/libpanel-util/panel-xdg.c
mate-panel/panel-toplevel.c

reported by cppcheck:
```
mate-panel/libpanel-util/panel-xdg.c:124:13: style: Variable 'current' is reassigned a value before the old one has been used. [redundantAssignment]
current = TRUE;
^
mate-panel/libpanel-util/panel-xdg.c:121:12: note: current is assigned
current = FALSE;
^
mate-panel/libpanel-util/panel-xdg.c:124:13: note: current is overwritten
current = TRUE;
^
```
```
mate-panel/panel-toplevel.c:779:15: style: Variable 'x_centered' is reassigned a value before the old one has been used. [redundantAssignment]
x_centered = abs (x - ((monitor_geom.width - width) / 2))
^
mate-panel/panel-toplevel.c:769:13: note: x_centered is assigned
x_centered = toplevel->priv->x_centered;
^
mate-panel/panel-toplevel.c:779:15: note: x_centered is overwritten
x_centered = abs (x - …
```

 Variable is reassigned a value before the old one has been used

---

applets/notification_area/status-notifier/sn-item-v0.c
mate-panel/libpanel-util/panel-icon-chooser.c
mate-panel/panel-menu-items.c
mate-panel/panel-multimonitor.c
mate-panel/panel-toplevel.c

reported by cppcheck:
```
applets/notification_area/status-notifier/sn-item-v0.c:918:13: style: Local variable 'properties' shadows outer variable [shadowVariable]
mate-panel/libpanel-util/panel-icon-chooser.c:398:9: style: Local variable 'path' shadows outer variable [shadowVariable]
mate-panel/libpanel-util/panel-icon-chooser.c:431:9: style: Local variable 'path' shadows outer variable [shadowVariable]
mate-panel/panel-multimonitor.c:224:16: style: Local variable 'geometries' shadows outer variable [shadowVariable]
mate-panel/panel-multimonitor.c:278:16: style: Local variable 'geometries' shadows outer variable [shadowVariable]
mate-panel/panel-multimonitor.c:107:22: style: Local variable 'geometries' shadows outer variable [shadowVariable]
```
reported by gcc:
``` …
```

Local variable shadows outer variable warning reported by cppcheck

---

applets/wncklet/org.mate.panel.applet.window-list.gschema.xml.in
applets/wncklet/window-list.c
applets/wncklet/window-list.ui

Add a new feature to window list preferences:  ```enable/disable``` mouse scrolling.
#1206 
```
make PR make install
pkill -f wnck-applet
mate-panel --replace
```
Window list preferences. Turn  ```Enabled Mouse Scroll``` on or off

Add window list disable mouse scrolling function

---

data/org.mate.panel.menubar.gschema.xml.in
mate-panel/panel-menu-items.c
mate-panel/panel-recent.c
mate-panel/panel-recent.h
mate-panel/panel-schemas.h

As requested by a fellow user on the Ubuntu MATE forum at https://ubuntu-mate.community/t/number-of-recent-documents/23802, the Recent Documents list in the Places menu on a panel should be of configurable length, since not all users want to see as few or as many as 10 recent documents in the menu.  This pull request resolves the issue.  The number of recently used documents displayed is determined by the value of the setting `org.mate.panel.menubar.max-recent-items` (default 10, like has been the default for years).

Make Recent Documents list in Places menu of configurable length

---

applets/wncklet/window-list.c
applets/wncklet/window-list.ui

Similar to #1221 
window-list.ui: use GtkNotebook
Set some callback functions in the ui file.
window-list.c: use g_settings_* functions directly instead of using stored values
use g_settings_bind when possible
For tabs to spaces I can do another PR, when this one is merged.

window-list: use GtkNotebook, improve codebase

---

applets/wncklet/workspace-switcher.c

This is just a "copy" of [this pr](https://github.com/mate-desktop/mate-panel/pull/752/), which adds xmonad to the supported wm.
It seems to work well on my Debian testing. 
(Replacing system "wnck-applet" with the new built "wnck-applet", restart, then the option "Show workspace names in switcher" appears.)

workspace-switcher: support xmonad WM

---

mate-panel/launcher.c
mate-panel/launcher.h

Add the function of monitor  panel launcher ```xxxxx.desktop``` files
When the launcher ```.desktop``` file changes, change the panel launcher synchronously
Fix #1235

Add the function of monitor panel launcher files

---

applets/clock/clock-location.c
applets/clock/clock.c

Fix clock applet add location crash
This PR needs to be tested with  [libmateweathe#100](https://github.com/mate-desktop/libmateweather/pull/100)
1. make  [libmateweathe#100](https://github.com/mate-desktop/libmateweather/pull/100) and install
2. make this pr and install
3. restart clock-applet and  mate-panel
4. clock-applet->edit->location->add

Fix clock applet add location crash

---

mate-panel/panel-run-dialog.c

Use g_get_home_dir function replace “~/”
Fix #1234

Use absolute path g_get_home_dir replaces "~/"

---

applets/wncklet/window-list.c
applets/wncklet/window-list.ui

I messed up somewhat with commit bcfc5255b55e9b3630ab1447defaa6f4edcfc65c: I did not notice that they used the `::changed` signal on purpose to make the properties dialog work even when changing the settings in dconf-editor for example.
This PR reverts that commit but retains the UI file changes (GtkNotebook) made in https://github.com/mate-desktop/mate-panel/pull/1223 and fixes the thumbnails checkbox (which had no effect before #1223 ).
Please test that all options are remembered after `mate-panel --replace` and that the properties dialog respond to changes made with dconf-editor.
Fixes #1250 (This should probably be in 1.26.1)

Fix window list

---

libmate-panel-applet/mate-panel-applet-factory.c
libmate-panel-applet/mate-panel-applet.c
mate-panel/main.c
mate-panel/mate-desktop-item-edit.c
mate-panel/panel-test-applets.c
mate-panel/xstuff.c

```
gpm-main.c:175:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-prefs.c:74:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-statistics.c:1211:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
--
gpm-backlight-helper.c:174:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL}
^
[robert@fedora builddir]$ grep -A 2 Wmissing-field-initializers] mate-panel.make.log
eggtreemultidnd.c:75:9: warning: missing field 'value_table' initializer [-Wmissing-field-initializers]
};
^
--
eggsmclient.c:261:16: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
main.c:62:10: warning: …
```

Fix build warnings about missing field initializer

---

mate-panel/panel-test-applets.c

```
LeakSanitizer: detected memory leaks
Direct leak of 1258 byte(s) in 32 object(s) allocated from:
#0 0x7ff30fb8c93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7ff30e776b7f in g_malloc ../glib/gmem.c:106
#2 0x7ff30e776ec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7ff30e7991a5 in g_strdup ../glib/gstrfuncs.c:364
#4 0x409787 in setup_options /home/robert/builddir.gcc/mate-panel/mate-panel/panel-test-applets.c:289
#5 0x409ec1 in main /home/robert/builddir.gcc/mate-panel/mate-panel/panel-test-applets.c:388
#6 0x7ff30e538b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
Direct leak of 512 byte(s) in 32 object(s) allocated from:
#0 0x7ff30fb8c93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7ff30e776b7f in g_malloc ../glib/gmem.c:106
#2 0x7ff30e776ec2 in g_malloc_n …
```

panel-test-applets: fix memory leak

---

applets/clock/clock.c

`if (oldvalue != cd->speed_unit)` should be `if (oldvalue != cd->temperature_unit)` in `temperature_unit_changed`

clock: fix temperature_unit_changed and -Wsign-compare warnings

---

applets/clock/clock-location-tile.c
applets/clock/clock.c
applets/clock/system-timezone.c
applets/notification_area/main.c
applets/wncklet/showdesktop.c
applets/wncklet/wayland-backend.c
applets/wncklet/window-list.c
applets/wncklet/window-menu.c
applets/wncklet/workspace-switcher.c
libmate-panel-applet/mate-panel-applet.c
libmate-panel-applet/test-dbus-applet.c
mate-panel/applet.c
mate-panel/launcher.c
mate-panel/libpanel-util/panel-error.c
mate-panel/libpanel-util/panel-icon-chooser.c
mate-panel/mate-desktop-item-edit.c
mate-panel/menu.c
mate-panel/panel-addto.c
mate-panel/panel-context-menu.c
mate-panel/panel-ditem-editor.c
mate-panel/panel-menu-bar.c
mate-panel/panel-menu-items.c
mate-panel/panel-recent.c
mate-panel/panel-toplevel.c
mate-panel/panel-widget.c
mate-panel/panel.c
mate-panel/xstuff.c

In addition, use dashes for signals: applet-added, applet-removed, applet-move, back-change, size-change

Remove unnecessary cast in g_signal_connect* call

---

applets/clock/calendar-window.c

```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fc2ab23a93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fc2a9d131bf in g_malloc ../glib/gmem.c:106
#2 0x7fc2a9d13502 in g_malloc_n ../glib/gmem.c:344
#3 0x7fc2a9d35995 in g_strdup ../glib/gstrfuncs.c:364
#4 0x40eee9 in calendar_window_set_prefs_path /home/robert/builddir.gcc/mate-panel/applets/clock/calendar-window.c:622
#5 0x40d949 in calendar_window_set_property /home/robert/builddir.gcc/mate-panel/applets/clock/calendar-window.c:390
#6 0x7fc2a9e29629 in object_set_property ../gobject/gobject.c:1571
#7 0x7fc2a9e2e024 in g_object_constructor ../gobject/gobject.c:2331
#8 0x40d3a5 in calendar_window_constructor /home/robert/builddir.gcc/mate-panel/applets/clock/calendar-window.c:315
#9 0x7fc2a9e2ecc1 in …
```

clock: fix memory leak

---

mate-panel/panel-run-dialog.c

`d_name` is never NULL since it points to a character array.
```
panel-run-dialog.c:1320:14: warning: address of array 'dent->d_name' will always evaluate to 'true' [-Wpointer-bool-conversion]
if (!dent->d_name ||
~~~~~~~^~~~~~
```
```
struct dirent {
ino_t          d_ino;       /* Inode number */
off_t          d_off;       /* Not an offset; see below */
unsigned short d_reclen;    /* Length of this record */
unsigned char  d_type;      /* Type of file; not supported
by all filesystem types */
char           d_name[256]; /* Null-terminated filename */
};
```
https://man7.org/linux/man-pages/man3/readdir.3.html
```
The buffer must be large enough for a struct dirent with a d_name array with {NAME_MAX} + 1 elements.
```
https://www.freebsd.org/cgi/man.cgi?query=readdir&sektion=3&manpath=fre …

panel-run-dialog: address of array 'dent->d_name' will always evaluate to 'true'

---

applets/notification_area/testtray.c

```
testtray.c:89:49: warning: cast from function call of type 'gint' (aka 'int') to non-matching type 'GtkOrientation' [-Wbad-function-cast]
GtkOrientation orientation = (GtkOrientation) gtk_combo_box_get_active (combo);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://docs.gtk.org/gtk3/method.ComboBox.get_active.html

notification_area: fix build warning -Wbad-function-cast

---

applets/wncklet/window-list.c

The values stored in the lookup hash table (`display_x11->xid_ht`) are no longer valid after 06292db.
gdk/x11/gdkwindow-x11.c
```
GdkWindow *
gdk_x11_window_foreign_new_for_display (GdkDisplay *display,
Window      window)
{
...
if ((win = gdk_x11_window_lookup_for_display (display, window)) != NULL) /* search in the lookup table */
return g_object_ref (win);
...
win = _gdk_display_create_window (display);
win->impl = g_object_new (GDK_TYPE_WINDOW_IMPL_X11, NULL);
....
g_object_ref (win);
_gdk_x11_display_add_window (display, &GDK_WINDOW_XID (win), win); /* add in the lookup table */
....
return win;
}
```
gdk/x11/gdkxid.c
```
void
_gdk_x11_display_add_window (GdkDisplay *display,
XID        *xid,
GdkWindow  *data)
{
...
g_hash_table_insert (display_x11->xid_ht, xid, data);
}
```
``` …
```

wncklet: The values stored in the wrapper hash table are incorrect

---

applets/notification_area/system-tray/na-tray-child.c
applets/wncklet/showdesktop.c
mate-panel/button-widget.c
mate-panel/panel-action-button.c
mate-panel/panel-applet-frame.c
mate-panel/panel-background.c
mate-panel/panel-config-global.c
mate-panel/panel-lockdown.c
mate-panel/panel-menu-button.c
mate-panel/panel-menu-items.c
mate-panel/panel-toplevel.c
mate-panel/panel-widget.c

```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum
```
```
panel-widget.c:1692:18: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
panel-widget.c:2496:16: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
panel-widget.c:2602:25: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
panel-widget.c:2825:25: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
panel-widget.c:2848:21: warning: implicit conversion …
```

Fix implicit conversion changes signedness: 'gboolean' to 'guint'

---

applets/clock/clock.c

```
git submodule init
git submodule update --recursive --remote
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
Fix the build warning below:
```
clock.c:1825:23: warning: cast from function call of type 'gdouble' (aka 'double') to non-matching type 'int' [-Wbad-function-cast]
value = (int) gtk_adjustment_get_value (adj);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

clock: cast from function call of type 'gdouble' to non-matching type

---

mate-panel/panel-multimonitor.c

```
cppcheck --enable=all -q .
```
Fix the cppcheck warning below:
```
mate-panel/panel-multimonitor.c:255:27: style: Condition '*monitors_ret>0' is always false [knownConditionTrueFalse]
if (res && *monitors_ret > 0)
^
mate-panel/panel-multimonitor.c:245:18: note: Assignment '*monitors_ret=0', assigned value is 0
*monitors_ret = 0;
^
mate-panel/panel-multimonitor.c:255:27: note: Condition '*monitors_ret>0' is always false
if (res && *monitors_ret > 0)
^
```

panel-multimonitor: Condition '*monitors_ret>0' is always false

---

applets/wncklet/showdesktop.c

```
cppcheck --enable=all -q .
```
Fx the cppcheck warning below:
```
applets/wncklet/showdesktop.c:376:23: style: Condition 'sdd->wnck_screen!=NULL' is always false [knownConditionTrueFalse]
if (sdd->wnck_screen != NULL)
^
applets/wncklet/showdesktop.c:369:21: note: Assignment 'sdd->wnck_screen=NULL', assigned value is 0
sdd->wnck_screen = NULL;
^
applets/wncklet/showdesktop.c:376:23: note: Condition 'sdd->wnck_screen!=NULL' is always false
if (sdd->wnck_screen != NULL)
^
```

wncklet: Condition 'sdd->wnck_screen!=NULL' is always false

---

mate-panel/panel-toplevel.c

fix undefined reference to g_clear_signal_handler (glib < 2.62)

---

applets/notification_area/na-grid.c

From time to time, I'm testing some third-party SNI implementations (just for the sake of knowledge) on my favorite DE ( ;) ) and observed that with `enable-sni-support = false`, default applet still registers SNI host and if SNI watcher of other tray implementation accepts registration from that applet, tray icons being duplicated. In practice, I discovered this with the xapp's applet.

Register SNI host only if SNI is enabled

---

applets/wncklet/window-list.c

Fixes https://github.com/mate-desktop/mate-desktop/issues/478

wncklet: Fix crash thumbnailing dying or otherwise inaccessible windows

---

data/default.layout
data/fedora.layout
data/linuxmint.layout
data/mageia.layout
data/opensuse.layout
data/org.mate.panel.object.gschema.xml.in
data/ubuntu.layout
mate-panel/applet.c
mate-panel/applet.h
mate-panel/drawer.c
mate-panel/launcher.c
mate-panel/panel-action-button.c
mate-panel/panel-applet-frame.c
mate-panel/panel-enums-gsettings.h
mate-panel/panel-layout.c
mate-panel/panel-menu-bar.c
mate-panel/panel-menu-button.c
mate-panel/panel-profile.c
mate-panel/panel-profile.h
mate-panel/panel-schemas.h
mate-panel/panel-separator.c
mate-panel/panel-toplevel.c
mate-panel/panel-widget.c
mate-panel/panel-widget.h
mate-panel/panel.c
mate-panel/panel.h

Conventionally, the applets on a MATE Panel are positioned relative to the
left edge of the panel (if the panel is horizontal) or the top edge (if the
panel is vertical).  There has also been some (buggy) support for positioning
of applets relative to the right (or bottom) edge of the panel, so that
applets on the right side of the panel will stay on the right side even if
the user changes screen resolutions or if the panel changes size for some
other reason.
However, many users want to also place applets at or near the center of their
panel(s).  There is no such conventional support for positioning applets
relative to the center of the panel, so users have positioned applets near
the center of the panel -- but the position recorded is relative to the left
side of the panel.  As such, the …

Add "center-stick" capability applets on the panel

---

applets/clock/clock.c
libmate-panel-applet/mate-panel-applet.c

Fix a leak in the clock applet (`gtk_style_context_get()` return values are owned by the caller), and in the no-background code path for all applets ([`gdk_window_set_background_pattern()`](https://docs.gtk.org/gdk3/method.Window.set_background_pattern.html) gets its own reference to the given pattern, so we need to release our own).
IMO the commits make more sense split as they are here, so I'd advise a rebase (rather than a squash).

Fix two leaks

---

mate-panel/panel-widget.c

Fix center- and right-sticking of expanding applets
In a prior commit (38e00280e9d17282717595a05411736a308804c0), I added support to stick applets to the center of the panel, so that no matter the width of the applet or the panel, the applet would always stay at the center of the panel.  That commit also added an "end-relative" mode, which is similar to the panel's old "right-stick" feature, except end-relative mode positions the applet's right edge relative to the panel's right edge, whereas right-sticking positioned the applet's left edge relative to the right edge of the panel.  The advantage of end-relative positioning is that the applet can resize without moving itself even further to the right than the user intended, whereas if positioned so that there is empty space between the …

Fix center- and right-sticking of expanding applets

---

applets/wncklet/window-list.ui

Using gtk+-3.24 prevent starting the windows-list-preferences window in rhel8. See https://bugzilla.redhat.com/show_bug.cgi?id=2149747
Using gtk+-3.22 fixes the issue.
New version is checked with glade

windows-list.ui: lower gtk3 required version

---

mate-panel/panel-menu-button.c

leave the code in place so it can be uncommented and used for further work on wayland

panel-menu-button: comment out wayland debugging message

---

applets/wncklet/window-list.c

Turns out the off-by-one issue when scaling is enabled can be easily fixed by getting the pointer position as a double: https://docs.gtk.org/gdk3/method.Device.get_position_double.html 
This PR also includes https://github.com/mate-desktop/mate-panel/pull/1348 to make testing easier but let me know if you'd prefer otherwise.
I've tested this with scaling, grouping, and multiple monitors in various positions.

wncklet: center previews when scaling is enabled

---

mate-panel/panel-run-dialog.c

Following up on https://github.com/mate-desktop/mate-panel/issues/1354, this PR adds shortcuts to each search hit:
Pressing the shortcut key selects the corresponding program, which can then be run by pressing enter. This makes it possible to leverage the fuzzy search to run applications without touching the mouse or pressing tab several times to select the list first and then the desired item.

panel-run-dialog: Add accelerator keys for "list of known applications"

---

applets/wncklet/wayland-backend.c

Add a basic shared context menu.
I could only verify 'close' on sway because it doesn't support set_minimize or set_maximize but they should work just fine.
This is my first time doing anything with GTK so please verify g_new0 / gtk_widget_destroy / g_free is working as intended and it neither leaks memory nor tries to access free'd memory.

applets/wncklet/wayland-backend: Add basic context menu

---

applets/wncklet/wayland-backend.c

This commit uses GTK to find an icon with the same name as the wayland app_id.
A more complete implementation would need to search for .desktop files matching the app_id, get the icon name and finally use GTK to find the proper icon based on that name.
For a discussion about this topic see https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/52

applets/wncklet/wayland-backend: Add basic icon support

---

applets/clock/clock.c
libmate-panel-applet/mate-panel-applet-gsettings.c
libmate-panel-applet/mate-panel-applet-gsettings.h
mate-panel/panel-profile.c

support for dconf-editor relocatable schemas

tell dconf-edit about relocatable schemas

---

applets/clock/Makefile.am
applets/fish/Makefile.am
applets/notification_area/Makefile.am
applets/wncklet/Makefile.am

Fix distribution of the applet service files sources when building from an in-process-configured build.  This fixes `make distcheck` and tarballs in builds configured with `--with-in-process-applets=all` (or actually any in-process applet).
The issue was that the .service.in file was referenced indirectly in EXTRA_DIST, and the variable listed there was only filled in a conditional.  Automake is not able to resolve this and see it still should distribute the reference of that variable, even if set conditionally.  Fix this by always setting the variable properly, even if it's only used for out-of-process builds.

Fix distribution of applet service files

---

libmate-panel-applet/Makefile.am

With gettext-0.22 we are getting build errors like: /usr/bin/msgfmt --desktop --keyword Name --keyword Description --template org.mate.panel.TestApplet.mate-panel-applet.desktop.in -d ../po -o org.mate.panel.TestApplet.mate-panel-applet /usr/bin/msgfmt: no input file should be given if --desktop and -d are specified Try '/usr/bin/msgfmt --help' for more information. make[3]: *** [Makefile:1035: org.mate.panel.TestApplet.mate-panel-applet] Error 1 make[3]: *** Waiting for unfinished jobs....
Bug: https://bugs.gentoo.org/908877

libmate-panel-applet/Makefile.am: Fix build with gettext 0.22

---

applets/wncklet/wayland-backend.c

*Allows window buttons to dynamically resize themselves as the window list fills up instead of pushing all the other applets to the end of the panel. 
*add the #tasklist-button widget name to tasklist buttons in wayland, it was only being applied in x11. This makes it much easier to theme

wayland: Fix overflowing window list and ensure it can be themed

---

applets/notification_area/main.c

*Use automatic signal handling for changing icon size so this code doesn't get called when the applet is removed

notification-area: stop warning on removal

---

libmate-panel-applet/mate-panel-applet.c

* There is only one screen in GTK 3.22 or later
* Finding the screen from that used by GtkPanelPlug is out of process only
* Any in-process applet calling mate_panel_applet_request_focus needs this to avoid a segfault
* One known user: dictionary applet

libmate-panel-applet: don't use panel plug to find the screen

---

mate-panel/panel-force-quit.c

Center the force-quit dialog on x11 on hidpi displays. Stop it from running off the bottom right corner

Hidpi x11: center panel force-quit popup window

---

mate-panel/panel-force-quit.c

*Compute the size of the monitor we are actually showing the popup on *by getting the monitor it is shown on and running gdk_monitor_get_geometry()
*This returns application (scaled) pixels not device pixels and apparently so does gtk_widget_get_allocation()
*Thus we no longer have to compute the scale ourselves and the popup window centers on the panel's monitor
*Previously we got the rectangle covering ALL monitors and centered on that

Force-quit/x11: Fix misalignment of popup with multimonitors

---

mate-panel/panel-action-button.c

*For some reason "widget" is not being properly passed to this, so use NULL for the parent window
*This makes the "force-quit only available in x11" dialog work

Wayland: Fix force-quit unsupported message dialog

---

mate-panel/panel-menu-items.c

After replacing gtk_image_menu_item with mate_image_menu_item 
We must also replace 
GTK_TYPE_IMAGE_MENU_ITEM
with
MATE_TYPE_IMAGE_MENU_ITEM
This fixes leftover GtkImageMenuItem deprecation warnings and restores missing Places and System icons in main menus

Main menus: fix missing Places, System icons

---

applets/notification_area/status-notifier/sn-dbus-menu-item.c
applets/notification_area/status-notifier/sn-dbus-menu-item.h
applets/notification_area/status-notifier/sn-dbus-menu.c
applets/notification_area/status-notifier/sn-item-v0.c

Fixes #1412.
This PR also includes 2 unrelated typo fixes extracted from gnome-panel.  I can move remove them from this PR if wanted, as they are unrelated (and not necessary for anything but not having typos in the code).

status-notifier: Show AttentionIcon when Status is NeedsAttention 

---

applets/clock/calendar-window.c
applets/clock/clock.c
applets/notification_area/na-grid.c
applets/notification_area/status-notifier/sn-host-v0.c
applets/notification_area/status-notifier/sn-item-v0.c
applets/notification_area/system-tray/na-tray-manager.c
applets/wncklet/workspace-switcher.c
libmate-panel-applet/mate-panel-applet-gsettings.c
libmate-panel-applet/mate-panel-applet.c
mate-panel/button-widget.c
mate-panel/libmate-panel-applet-private/panel-applet-frame-dbus.c
mate-panel/libmate-panel-applet-private/panel-applets-manager-dbus.c
mate-panel/libpanel-util/panel-color.c
mate-panel/libpanel-util/panel-gtk.c
mate-panel/libpanel-util/panel-keyfile.c
mate-panel/mate-desktop-item-edit.c
mate-panel/panel-action-button.c
mate-panel/panel-background.c
mate-panel/panel-background.h
mate-panel/panel-lockdown.c
mate-panel/panel-menu-items.c
mate-panel/panel-multimonitor.c
mate-panel/panel-profile.c
mate-panel/panel-run-dialog.c
mate-panel/panel-test-applets.c
mate-panel/panel-widget.c
mate-panel/panel.c

All this was mostly found by cppcheck while I tried to improve its output in #1415.  Not everything it reports is taken care of here, but a lot is.

Various cleanups

---

applets/wncklet/workspace-switcher.c

Put the workspace switcher into a container so it can be properly sized without changing anything else in the panel.
All changes are in workspace-switcher.c

wnck-pager: Fix workspace switcher aspect ratio in a single file

---

mate-panel/panel-run-dialog.c

This code got introduced with 3c21f66bf30810fcb25dfe8c3c0960df270dc416 trying to mimic `gdk_spawn_on_screen()`, but does not: what `gdk_spawn_on_screen()` did (on X11) was to append the screen number to the display, so that it worked on a multi-screen setup where the app is not on the default X screen.
However, the code that got introduced just sets the display, which is gonna be already there anyway (yet possibly loosing the default screen in the process?), and AFAIK GDK dropped support for multi-screen setups anyway (not to be confused with multi-monitor with e.g. Xinerama).
We should actually be better of without any of this, as it most likely doesn't do what it is supposed to, nobody needs what it failed to do, and it breaks XWayland on Wayland.
Fixes #1387.
:warning: I didn't …

run-dialog: Don't needlessly override DISPLAY environment variable

---

libmate-panel-applet/mate-panel-applet.c

*Fix the window list menu replacing the panel context menu between the end of the window list and the next applet when running under wayland

wayland: keep window list menu off space not used for buttons

---

applets/wncklet/window-list.c

This function only loads the icon during the startup-notification, at
which point it gets replaced by the actual icon read in libwnck. Moving
forward the loading function should become part of libwnck.
Related: https://gitlab.gnome.org/GNOME/libwnck/-/merge_requests/55

wncklet: Remove icon loader function from window list applet

---

applets/notification_area/status-notifier/sn-item-v0.c

When loading an icon from a path rather than the icon theme, we scale it down to match the scale we need[^1], but we leaked the original pixbuf in this case.
Fixes #1444.
[^1]: See commit e5c8646d8f6167fe2d3634a4604a1bf9ec8ee5af

status-notifier: Plug large leak with icons from paths

---

libmate-panel-applet/mate-panel-applet-gsettings.c
mate-panel/panel-profile.c

We need to check the existence of dconf-editor's GSettings schema before using it, because the program will abort if dconf-editor is not installed on the system when it tries to access it.

Check the existence of dconf-editor's schema

---

.travis.yml

The CI error on master:
```
/home/travis/.rvm/gems/ruby-3.3.5/gems/cl-1.2.4/lib/cl/opts.rb:112:in `block in taint': undefined method `taint' for an instance of String (NoMethodError)
[key, self[key] && self[key].secret? ? value.taint : value]
^^^^^^
```
That error with Ruby 3 was fixed here: https://github.com/travis-ci/travis-cl/commit/e17a1b2bd2fe51eb9cc4fd90d19c8a12997717a0#diff-ee038a05d1feba327913a56ad3533ada6845400f2aa2a1b2b2d2584d4e2852ba
I'm hoping that bumping from https://github.com/travis-ci/dpl/releases/tag/v2.0.3-beta.4 to https://github.com/travis-ci/dpl/releases/tag/v2.0.5 pulls in the fix.

ci: Bump dpl branches for Ruby 3 support

---

applets/clock/clock-location-tile.c
applets/clock/clock.c

%l is an glibc extension for strftime, this extensions isn't supported by musl libc.
Replace %l with %_I, which is functionaly equivalence. %_I itself is also an extensions, however, %_I is supported by both glibc, musl, FreeBSD and deriviates, AIX, and Solaris.
Fix: #1451

applets/clock: Fix compatibility with musl libc

---

applets/clock/clock.c
applets/clock/clock.ui

Before this pull request, the Clock Applet's popup window would expand off the screen if the user added more than a few locations to the Locations list. In addition, the list of locations in the Clock Applet Preferences could get extremely tall as well, and could even push the bottom part of the Preferences dialog off the screen.
This PR adds (vertical) scrollbars to both widgets.  Here's how the Clock Applet popup looks now:
And here is how the Preferences dialog looks now:

Clock Applet: Add scrollbar to Locations lists when the lists get too long

---

applets/clock/Makefile.am
applets/clock/calendar-client.c
applets/clock/calendar-client.h
applets/clock/calendar-debug.h
applets/clock/calendar-sources.c
applets/clock/calendar-sources.h
applets/clock/calendar-window.c
applets/clock/calendar-window.h
applets/clock/clock.c
applets/clock/clock.ui
applets/clock/org.mate.panel.applet.clock.gschema.xml.in
configure.ac
mate-panel/panel-test-applets.c

Add Evolution Data Server (EDS) calendar integration to the MATE panel clock applet, most of it ~ported~ copy/pasted from gnome-panel's clock applet. This allows users to view calendar events and tasks directly from the clock popup calendar.
The calendar integration is disabled by default and can be enabled with --enable-eds during configuration. When disabled, the clock applet functions normally without any EDS dependencies.
_Note: This requires the changes in https://github.com/mate-desktop/libmateweather/pull/133 (libedataserver requires libsoup-3 to work and it otherwise conflicts with the weather display using libsoup2)_
Fixes #480

clock: Backport Evolution calendar integration from gnome-panel

---

mate-panel/panel-toplevel.c

Disable grabbing and moving expanded panels with the mouse in wayland due to tendency of panel other than on top to jump to top or left

wayland: stop panel "dodging" mouse and moving to top or left

---

applets/clock/clock.c
applets/fish/fish.c
applets/wncklet/window-list.c
mate-panel/panel-toplevel.c

A previous overzealous cleanup left some hanging screen variables and one instance of an uninitialized screen being used.

Fix uninitialized and unused screen vars

---

applets/clock/calendar-client.c
applets/clock/calendar-client.h
applets/clock/calendar-window.c
applets/clock/calendar-window.h
applets/clock/clock.c

This simplifies the evolution calendar client architecture and makes the popup show up faster, since we don't need to create a new one every time we open it.

clock: Store calendar client in ClockData

---

applets/clock/calendar-window.c
applets/clock/org.mate.panel.applet.clock.gschema.xml.in

The Appointments and Tasks expanders in the calendar popup were incorrectly linked to the show-calendar-events and show-tasks gsettings. This caused collapsing the section to toggle the preference, making the entire section disappear on next popup.
Fixed by adding a new expand-calendar-events and expand-tasks gsettings keys to track the UI state separately from whether the section is visible or not.

clock: Separate expander state from section visibility preferences
