mate-desktop/mate-panel

mate-panel/panel-force-quit.c
This patch implements handling of XInput2 extension events in the applet.
Without this patch, the applet fails to recognize such events (either mouse
click for killing application, or escape key for exiting), hence freezing the
desktop.
Also fix the event mask in call of gdk_device_grab() for keyboard.
Author: Sébastien Villemot <sebastien@debian.org>
http://bugs.debian.org/698740
Original commit in gnome-panel:
https://git.gnome.org/browse/gnome-panel/commit/?id=5a8583a77aab91fe1a369becc9453b27bf30ee70
=> Fix Force-Quit panel applet to avoid hang with GTK3

mate-panel/panel-toplevel.c
the problem is described in https://github.com/mate-desktop/mate-panel/issues/44#issuecomment-116635132, this PR fixes it for me.
@flexiondotorg @infirit @NiceandGently 
please test
=> drawer: now opens fine after adding any applets and restarting session

mate-panel/panel-run-dialog.ui
- this fixes program list in GTK3
=> UI GTK3: use a size request for scrolled window in panel-run dialog

applets/clock/clock.c, applets/fish/fish.c, applets/notification_area/main.c, applets/wncklet/showdesktop.c, applets/wncklet/window-list.c, applets/wncklet/window-menu.c, applets/wncklet/workspace-switcher.c, mate-panel/panel-context-menu.c
As there is more than 1 file changed, this should be tested, of course for gtk2 too.
=> use GtkAbout for applets

mate-panel/panel-toplevel.c
Not sure if this is the right fix, but was able to get it building with Gtk 3.18 this way.
=> Fix FTBFS with Gtk 3.18

applets/clock/calendar-window.c
shows up **bold** in Green-Submarine theme.
=> clock-applet: mark current day

mate-panel/applet.c
=> Fix: the panel does not display the icon on the mouse with dnd

mate-panel/button-widget.c
https://github.com/mate-desktop/mate-panel/issues/359
=> Gtk-WARNING: Allocating size to GtkAlignment..

applets/notification_area/libstatus-notifier-watcher/gf-sn-watcher-v0.c
Doesn't account for all of @XRevan86 reports yet, but I'll need more info.  Still, this one fixes a real and fairly constant, yet not huge, leak.
=> status-notifier: Plug a memory leak

mate-panel/panel-menu-bar.c, mate-panel/panel-menu-button.c
=> Fix: menubar/menu-button can't launch mozo

mate-panel/menu.c
Fix https://github.com/mate-desktop/mate-panel/issues/305
=> Fix closing of main menu

applets/clock/clock.c, mate-panel/panel-multiscreen.c
Use `gdk_display_get_n_monitors` instead
since gtk 3.22
=> avoid deprecated gdk_screen_get_n_monitors

libmate-panel-applet/mate-panel-applet.c
Out-of-process applets end up scaled up doubly. This divides the preferred width/height by the scale factor to ensure they are back at the correct preferred size.
For this change I had to move the GTK_VERSION guards on the `get_preferred_width/height` methods. The methods are now exposed, but the focus style class padding is still guarded.
=> Down-scale out-of-process applets on HiDPI displays

libmate-panel-applet/mate-panel-applet.c
=> Added gir for mate_panel_applet_set_size_hints()

mate-panel/panel-run-dialog.c
=> Run dialog accessibility

mate-panel/panel-run-dialog.c
learning signal chaining...
fix for #725
=> Fix run dialog show-program-list enabling fix

applets/wncklet/window-list.c, applets/wncklet/workspace-switcher.c
Fix #754 
Don't show the applet until it's size has been determined including any hidpi scaling
=> Fix rendering of out-of-process window list with hidpi

applets/wncklet/workspace-switcher.c
Fixes https://github.com/mate-desktop/mate-panel/issues/711
=> workspace-switcher: support i3 WM

applets/clock/clock.ui
avoid deprecated:
GtkTable
GtkVBox
GtkHBox
GtkVButtonBox
GtkHButtonBox
GtkButton:use-stock
GtkImage:stock
=> clock.ui: avoid deprecated:

applets/fish/fish.ui
avoid deprecated:
GtkVBox
GtkHBox
GtkTable
GtkLabel:ypad
GtkButton:use-stock
=> fish.ui: avoid deprecated:

mate-panel/panel-toplevel.c
fix for https://github.com/mate-desktop/mate-panel/issues/786
=> limit size of panel-hide-button

mate-panel/drawer-private.h, mate-panel/drawer.c, mate-panel/drawer.h, mate-panel/menu.c, mate-panel/panel-addto.c, mate-panel/panel-menu-button.c, mate-panel/panel-run-dialog.c
Please review and see this [PR](https://github.com/mate-desktop/mate-menus/pull/59).
=> support mate-menus api change

applets/wncklet/workspace-switcher.c
When a theme does not specify a color for the highlighted workspace, we can look it up from the current theme and provide that as a fallback color.
Fixes #807
=> workspace-switcher: provide themed fallback color

mate-panel/panel-force-quit.c
=> panel-force-quit: fix some GDK deprecations

applets/notification_area/system-tray/na-tray-child.c, libmate-panel-applet/mate-panel-applet.c, mate-panel/main.c, mate-panel/panel-util.c, mate-panel/panel-widget.c, mate-panel/panel-xutils.c
=> more GDK deprecation fixes

mate-panel/libpanel-util/panel-session-manager.c
=> Check if manager->proxy is NULL

mate-panel/libpanel-util/panel-gtk.c
'g_strconcat' needs to be freed
=> panel-gtk: Fix memory leaks

configure.ac, mate-panel/wayland-protocols/Makefile.am
Should fix the problem noted here: https://github.com/mate-desktop/mate-panel/pull/899#issuecomment-447844869
=> Replace wayland-scanner private-code option with code

libmate-panel-applet/Makefile.am, libmate-panel-applet/mate-panel-applet-factory.c, libmate-panel-applet/mate-panel-applet.c, libmate-panel-applet/mate-panel-applet.h, libmate-panel-applet/panel-applet-private.h, libmate-panel-applet/panel-plug-private.h, libmate-panel-applet/panel-plug.c
Required for future Wayland support
=> Libmate-panel make X dependecies optional

applets/Makefile.am, applets/clock/clock-location-tile.c, applets/clock/clock.c, applets/notification_area/main.c, applets/notification_area/na-grid.h, applets/notification_area/system-tray/na-tray-child.c, applets/notification_area/system-tray/na-tray-child.h, applets/notification_area/system-tray/na-tray-manager.c, applets/notification_area/system-tray/na-tray.c, applets/notification_area/system-tray/na-tray.h, applets/wncklet/showdesktop.c, applets/wncklet/wncklet.c
Various fixes for running applets on non-X11 (read: Wayland) platforms.
=> Wayland support for applets

.travis.yml
=> Enable Travis CI support

.travis.yml
The new docker-build: mate-desktop/mate-dev-scripts#11
=> Test the new docker-build

libmate-panel-applet/mate-panel-applet.c, mate-panel/menu.c
We need this for future porting of tray icons to standalone applets as replacements dfor gtk_menu_popup emit a "popped-up" signal when the menu is showing
Based on gnome-panel commit github.com/GNOME/gnome-panel/commit/8e6e2847eca002499e862e9ae85bbc4c16b601fa
Prior efforts at this did not work because using "NULL" for the event in gtk_menu_popup_at_widget got an invalid value and caused applet context menus to stay up only so long as the right-click mouse button was held down. GNOME fixed this the `button_press_event_new ` function
=> mate-panel-applet.c: replace deprecated gtk_menu_popup

libmate-panel-applet/panel-plug-private.h, mate-panel/launcher.c, mate-panel/panel-action-button.c, mate-panel/panel-applet-frame.c, mate-panel/panel-background.c, mate-panel/panel-bindings.c, mate-panel/panel-menu-bar.c, mate-panel/panel-menu-button.c, mate-panel/panel-run-dialog.c, mate-panel/panel-session.c, mate-panel/panel-util.c, mate-panel/panel-util.h, mate-panel/panel-widget.c, mate-panel/panel.c
This has a lot of the files that just need minor changes to support Wayland. It doesn't remove all X-specific code from the project and there is still no Wayland backend in place, so this should only be tested under X. If reviewers would like me to break this up into smaller pieces, just ask. Most of the commits are independent.
=> Wayland support for the easy files

.travis.yml
This PR enables `cppcheck` static analyzer in the logs
=> travis: enable 'cppcheck'

.travis.yml
with a docker-image with MATE 1.20
=> travis: use f28 with old libmatemenu

applets/notification_area/system-tray/fixedtip.c
=> Na-tray deprecations

mate-panel/panel-menu-bar.c, mate-panel/panel-menu-button.c, mate-panel/panel-util.c, mate-panel/panel-util.h
This revert
https://github.com/mate-desktop/mate-panel/commit/f0f4c5e
and fixes https://github.com/mate-desktop/marco/issues/209
Please test.
=> revert menu-bar: transfer focus correctly on alt-F1

mate-panel/panel-a11y.c, mate-panel/panel-a11y.h
Update [FSF address](https://www.fsf.org/about/contact/)
=> Update FSF address

applets/notification_area/main.h, mate-panel/panel-a11y.c, mate-panel/panel-a11y.h
Update [FSF address](https://www.fsf.org/about/contact/)
=> Udpate FSF address

applets/notification_area/system-tray/fixedtip.c, applets/notification_area/system-tray/na-tray.h, libmate-panel-applet/mate-panel-applet-factory.c, libmate-panel-applet/mate-panel-applet.c, mate-panel/Makefile.am, mate-panel/libegg/eggdesktopfile.c, mate-panel/libegg/eggsmclient-xsmp.c, mate-panel/libmate-panel-applet-private/panel-applet-container.c, mate-panel/main.c, mate-panel/panel-layout.c, mate-panel/panel-profile.c, mate-panel/panel-struts.c, mate-panel/panel-struts.h, mate-panel/panel-toplevel.c, mate-panel/panel-widget.c
Update a bunch of files in preparation for Wayland support. As with my other PRs you can't test Wayland support yet, just make sure it doesn't break anything on X11.
=> Prep for wayland

applets/clock/clock.c
=> [clock-applet] Add scroll interface tabs with mouse wheel

.travis.yml
=> ci: fix build error on travis for gtk-layer-shell

mate-panel/panel-widget.c
=> When determining whether the pos is in the applet, use ad->cells to calc.

applets/clock/clock-face.c
- replace tabs with spaces
- fix a few indentation
- reduce leading spaces (8 --> 4)
fixes https://github.com/mate-desktop/mate-panel/pull/1016#discussion_r324455229
=> clock-face: fix code formating

applets/clock/Makefile.am, applets/fish/Makefile.am, applets/wncklet/Makefile.am, libmate-panel-applet/Makefile.am, mate-panel/Makefile.am
Fixed: Some UI elements are not translated.
More info:
https://github.com/mate-desktop/mate-panel/pull/1037#issuecomment-554139927
https://github.com/mate-desktop/mate-panel/pull/1037#issuecomment-554258319
=> fix mate-panel can not find mo file

mate-panel/panel-addto.c
=> Enable applications in addto menu

applets/clock/Makefile.am, applets/fish/Makefile.am, applets/notification_area/Makefile.am, applets/wncklet/Makefile.am, mate-panel/Makefile.am
Test:
```shell
$ find . -name *.mate-panel-applet -exec cat {} +
$ cat mate-panel/mate-panel.desktop
```
=> Do not collect the translation for Icon

applets/clock/clock-utils.c, applets/clock/clock.c, applets/clock/set-timezone.c, applets/notification_area/libstatus-notifier-watcher/gf-sn-watcher-v0.c, applets/notification_area/libstatus-notifier-watcher/gf-status-notifier-watcher.c, applets/notification_area/na-grid.c, applets/notification_area/na-host.c, applets/notification_area/na-item.c, applets/notification_area/status-notifier/sn-dbus-menu-item.c, applets/notification_area/status-notifier/sn-dbus-menu.c, applets/notification_area/status-notifier/sn-host-v0.c, applets/notification_area/status-notifier/sn-item-v0.c, applets/notification_area/status-notifier/sn-item.c, applets/notification_area/testtray.c, mate-panel/mate-desktop-item-edit.c, mate-panel/panel-stock-icons.c, mate-panel/panel-xutils.c
The config.h file is not in the same folder that uses it, the preprocessor searches in -I folders, there is only one config.h file.
=> Use '#include <config.h>' instead of '#include "config.h"'

Makefile.am, applets/notification_area/Makefile.am, applets/notification_area/system-tray/Makefile.am
test:
```
$ ./autogen.sh && make clean && git status | grep ".*\.[c|h]$"
```
=> build: Add built sources to CLEANFILES target

applets/clock/clock.c
Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188
=> clock: Simplify notebook scroll-event callback

applets/clock/clock.c
The sorting and reversing operations can be merged:
```C
/* Copy the existing list, so we can sort it nondestructively */
node = g_list_copy (cities); /* O(n) */
node = g_list_sort (node, sort_locations_by_time); /* O(n) */
node = g_list_reverse (node); /* O(n) */
```
```C
/* Copy the existing list, so we can sort it nondestructively */
node = g_list_copy (cities); /* O(n) */
node = g_list_sort (node, sort_locations_by_time_reverse); /* O(n) */
```
=> clock: sorting the selected locations by reverse time and name

mate-panel/launcher.c
Follow-up to #1126 to address [my review comment](https://github.com/mate-desktop/mate-panel/pull/1126#pullrequestreview-460780426), which is a very similar leak further down in the same file.
=> launcher: Fix memory leak

mate-panel/panel.c
Follow-up to #1130.
Don't propose actions that will fail anyway, and create a launcher automatically if it's the only option.  However, still ask for setting
the background to still avoid unintentional changes.
To test this, you need to [lock down](https://help.gnome.org/admin/system-admin-guide/stable/dconf-lockdown.html.en) the relevant settings (*/org/mate/panel/toplevels/top/background/image* and */org/mate/panel/general/object-id-list*).  **BEWARE** though: I somehow lost all my panel config by locking */org/mate/panel/general/object-id-list*, likely because I didn't hardcode a default value and dconf sudently reported an empty object-id-list, resulting in the panel removing a bunch of objects.  I partially recovered from a backup, but meh, still no fun.  If you wanna try, I highly …
=> Handle locked down settings better when dropping an image URI (#1130 follow-up)

applets/clock/clock.c, applets/fish/fish.c, applets/wncklet/showdesktop.c, applets/wncklet/window-list.c, applets/wncklet/window-menu.c, applets/wncklet/workspace-switcher.c, configure.ac
Test:
```
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
```
=> build: Use PACKAGE_URL variable

applets/notification_area/status-notifier/sn-item-v0.c
@raveit65  @yetist 
The notification area before modification can only display icons. This PR adds the text label display function.
The ```app_indicator_set_label```  API doesn't work before modification. After modification, the label can be displayed.
[Test code](https://github.com/mate-desktop/mate-panel/files/5891282/simple-test.tar.gz)
``` 
mkdir /tmp/test-dir
cp -rf simple-test.tar.gz  /tmp/test-dir/
cd  /tmp/test-dir/
tar -xvf simple-test.tar.gz
make
./test
````
After running, the icon and text will be displayed in the notification area
=> Add text label display function for notification area

mate-panel/panel-struts.c, mate-panel/panel-struts.h, mate-panel/panel-xutils.c, mate-panel/panel-xutils.h
This is a preparation for adding some commits from gnome-panel to fix https://github.com/mate-desktop/mate-panel/issues/303#issuecomment-808874551
This makes it better to clean apply those commits.
In the meanwhile i will prepare a PR for metacity.
=> Preparation wm strut area

mate-panel/panel-run-dialog.c
Using  ```gtk_entry_completion```  replaces that has been discarded ```g_ompletion```
By replacement, a lot of redundant code is removed
```
make pr && make install
Shortcut key Alt + F2
```
=> Replace deprecated GCompletion with GtkEntryCompletion 

mate-panel/panel-struts.c, mate-panel/panel-struts.h, mate-panel/panel-toplevel.c, mate-panel/panel-xutils.c, mate-panel/panel-xutils.h
=> struts: add support for _GNOME_WM_STRUT_AREA

applets/wncklet/window-list.c
Fixes #1315 
Instead of randomly positioning the preview windows over the window list applet this centers them properly.
I've tested it on Ubuntu 22.04, with all orientations, 2x scaling, many windows opened (so that previews are not cut off at the edges), and at least plugging in a secondary monitor didn't cause any issues either.
One thing that might be worth pointing out is `gtk_window_set_position + GTK_WIN_POS_MOUSE` followed by `gtk_window_get_position` returned incorrect coordinates: e.g. it was zero for the first about 40 pixels. So this gets the mouse position differently. This newer method is actually also used in `panel_toplevel_contains_pointer`.
The tooltips are still not aligned properly but I think that could be done in a follow up. Maybe even in `libwnck` instead. I might …
=> wncklet: center preview windows

applets/wncklet/window-list.c
When grouping is enabled all tasklist buttons are siblings of each other but the grouped ones shouldn't contribute to the width. These always have 1px height and width and x/y is -1 only when the group is not open. I'm not sure if there's a better way to distinguish these.
Also, annoyingly when grouping is enabled and the mouse is moved from left to right, and you stop over the very first pixel of the next button the preview will be positioned incorrectly above the previous button. This doesn't happen for every button, and I haven't been able to figure out why. I tried to detect the hover state to get around this with `GTK_STATE_FLAG_PRELIGHT` but `gtk_widget_get_state_flags (children->data);` returns a value of `GTK_STATE_FLAG_CHECKED` for every button all the time.
=> wncklet: center preview windows when grouping is enabled

applets/clock/clock.c
Before this commit, the Clock Applet was unaware of when the system resumed from sleep mode (e.g. suspend or hibernate).  This meant that, if the user suspended the system and then woke it up some time later, the clock might not show the real current time, but instead would continue to show the time at which the system was suspended for up to a minute after the system woke up.  This could be confusing to the user if they peered up at the clock immediately after, say, opening their laptop lid.
This commit connects to ConsoleKit or (if available) systemd-logind via D-Bus, and listens for a signal that indicates when the system wakes up from sleep mode.  When the system does wake up, the Clock Applet updates the date/time immediately, and also updates all the weather/temperature readings if …
=> Clock Applet: Update date/time and weather after resume from sleep mode

mate-panel/button-widget.c
Icons present in the icon theme are now handled by gtk_icon_theme_load_surface() so they render clear and sharp. This is basically all of the icons that will be in the menus and be draggable to the panel, and anything from /usr/share/applications dragged to the panel as well.
A custom icon (I use one for firefox runnng in RAM) not present in the icon theme and instead loaded from a file outside the normal icon directories is not findable by gtk_icon_theme_load_surface(), so the previous code was retained as a fallback to prevent such icons from disappearing. Such custom icons thus won't render crisply but all other will.
Very clear and sharp in x11 too
=> Wayland: Fix blurry rendering of panel launcher icons

mate-panel/button-widget.c, mate-panel/button-widget.h
=> button-widget.c: replace tabs with 4 spaces

data/org.mate.panel.object.gschema.xml.in
It was listing outdated values, and missing new ones.
Fixes #1132.
=> Update org.mate.panel.object schema descriptions

applets/wncklet/wayland-backend.c
*Empty space between buttons removed
*padding in buttons similar to x11
*Horizontal panel: expand buttons like in X11 until more expanded buttons won't fit *When expanded buttons won't fit, resize buttons to fit contents. Almost same behavior as x11 in hiding first labels, then icons with compressed labels returning as more buttons are added.
=> wayland tasklist:  fit buttons to tasklist, limit button size, hide contents as necessary

mate-panel/panel-action-button.c
*This uses systemd to be able to shutdown when root is logged in anywhere, possibly including display managers *If user login is only login shutdown and reboot work w/o systemd *Suspend requires systemd at this point
*Logind support would be welcome
=> Wayland: Make panel shutdown button work under wayland

mate-panel/panel-properties-dialog.c
=> Update opacity when changed gsettings color value

mate-panel/panel.c
Fix #870. Tested by rebuilding MATE 1.27 Debian source package.
Maybe the alpha value is no longer lost.
=> Fix dragging panel color
